def get_employee_custom_fields():
	return {
		"Employee": [
			{
				"depends_on": "eval:!doc.attendance_by_timesheet",
				"description": "If checked, the Employee can be selected as weekend reliever in Roster.",
				"fieldname": "custom_is_weekend_reliever",
				"fieldtype": "Check",
				"insert_after": "custom_is_reliever",
				"label": "Is Weekend Reliever",
			},
			{
				"fieldname": "custom_enable_face_recognition",
				"fieldtype": "Check",
				"insert_after": "checkin_location",
				"label": "Enable Face Recognition",
			},
			{
				"depends_on": "eval:!doc.attendance_by_timesheet",
				"description": "If checked, the Employee can be selected as day off reliever in Roster.",
				"fieldname": "custom_is_reliever",
				"fieldtype": "Check",
				"insert_after": "shift_working",
				"label": "Is Day Off Reliever",
			},
			{
				"depends_on": "eval:doc.shift",
				"fieldname": "custom_operations_role_allocation",
				"fieldtype": "Link",
				"insert_after": "shift",
				"label": "Operations Role Allocation",
				"mandatory_depends_on": "eval:doc.shift&&doc.shift_working&&!doc.custom_is_reliever",
				"options": "Operations Role",
			},
			{
				"fieldname": "custom_civil_id_assurance_level",
				"fieldtype": "Data",
				"insert_after": "one_fm_centralized_number",
				"label": "Civil ID Assurance Level",
				"read_only": 1,
				"translatable": 1,
			},
			{
				"fetch_from": "project.custom_payroll_end_date",
				"fieldname": "custom_payroll_cycle_end_date",
				"fieldtype": "Data",
				"insert_after": "custom_payroll_cycle_start_date",
				"label": "Payroll Cycle End Date",
				"translatable": 1,
			},
			{
				"fetch_from": "project.custom_payroll_start_date",
				"fetch_if_empty": 1,
				"fieldname": "custom_payroll_cycle_start_date",
				"fieldtype": "Data",
				"ignore_user_permissions": 1,
				"insert_after": "payroll_cost_center",
				"label": "Payroll Cycle Start Date",
				"read_only": 1,
				"translatable": 1,
			},
			{
				"default": "0",
				"fieldname": "registered",
				"fieldtype": "Check",
				"insert_after": "custom_enable_face_recognition",
				"label": "Registered",
				"module": "One Fm",
				"no_copy": 1,
				"read_only": 1,
			},
			{
				"fieldname": "column_break_heye",
				"fieldtype": "Column Break",
				"insert_after": "bank_name",
			},
			{
				"fieldname": "iban",
				"fieldtype": "Data",
				"insert_after": "one_fm_basic_salary",
				"label": "IBAN",
				"translatable": 1,
			},
			{
				"fieldname": "custom_employee_image",
				"fieldtype": "Image",
				"insert_after": "pam_type",
				"label": "Employee Image",
				"options": "custom_employee_photo",
			},
			{
				"fieldname": "custom_employee_photo",
				"fieldtype": "Attach Image",
				"insert_after": "under_company_residency",
				"label": "Employee Photo",
			},
			{
				"fieldname": "auto_attendance",
				"fieldtype": "Check",
				"insert_after": "attendance_by_timesheet",
				"label": "Auto Attendance",
				"read_only": 1,
			},
			{
				"fieldname": "non_kuwaiti_residents",
				"fieldtype": "Check",
				"hidden": 1,
				"insert_after": "auto_attendance",
				"label": "Non Kuwaiti Resident",
			},
			{
				"fetch_from": "employment_type.attendance_by_timesheet",
				"fieldname": "attendance_by_timesheet",
				"fieldtype": "Check",
				"insert_after": "number_of_days_off",
				"label": "Attendance by Timesheet",
			},
			{
				"fieldname": "employee_id",
				"fieldtype": "Data",
				"in_list_view": 1,
				"in_standard_filter": 1,
				"insert_after": "status",
				"label": "Employee ID",
				"read_only": 1,
				"unique": 1,
			},
			{
				"fieldname": "is_in_ows",
				"fieldtype": "Select",
				"insert_after": "employee_id",
				"label": "Is in OWS",
				"options": "\nYes\nNo",
				"translatable": 1,
			},
			{
				"fieldname": "health_insurance_provider",
				"fieldtype": "Table",
				"insert_after": "health_insurance_section",
				"is_system_generated": 1,
				"label": "Health Insurance Provider",
				"options": "Health Insurance Provider Detail",
			},
			{
				"depends_on": "eval:doc.under_company_residency==1",
				"fetch_from": "pam_file.pam_file_number",
				"fieldname": "pam_file_number",
				"fieldtype": "Data",
				"insert_after": "pam_file",
				"label": "PAM FIle Number",
				"read_only": 1,
				"translatable": 1,
			},
			{
				"depends_on": "eval:doc.under_company_residency==1",
				"fieldname": "pam_file",
				"fieldtype": "Link",
				"insert_after": "one_fm_pam_designation",
				"label": "PAM File",
				"options": "PAM File",
			},
			{
				"fieldname": "coulumn_break_ar2",
				"fieldtype": "Column Break",
				"insert_after": "department",
			},
			{
				"fieldname": "column_break_ar1",
				"fieldtype": "Column Break",
				"hidden": 1,
				"insert_after": "branch",
			},
			{
				"fieldname": "arabic_names",
				"fieldtype": "Section Break",
				"hidden": 1,
				"insert_after": "grade",
				"label": "Arabic Names",
			},
			{
				"fetch_from": "department.payroll_cost_center",
				"fetch_if_empty": 1,
				"fieldname": "payroll_cost_center",
				"fieldtype": "Link",
				"hidden": 1,
				"insert_after": "salary_cb",
				"is_system_generated": 1,
				"label": "Payroll Cost Center",
				"options": "Cost Center",
			},
			{
				"fieldname": "salary_cb",
				"fieldtype": "Column Break",
				"insert_after": "salary_mode",
				"is_system_generated": 1,
			},
			{
				"fieldname": "shift_request_approver",
				"fieldtype": "Link",
				"insert_after": "column_break_45",
				"is_system_generated": 1,
				"label": "Shift Request Approver",
				"options": "User",
			},
			{
				"fieldname": "column_break_45",
				"fieldtype": "Column Break",
				"insert_after": "leave_approver",
				"is_system_generated": 1,
			},
			{
				"fieldname": "leave_approver",
				"fieldtype": "Link",
				"insert_after": "expense_approver",
				"is_system_generated": 1,
				"label": "Leave Approver",
				"options": "User",
			},
			{
				"fieldname": "expense_approver",
				"fieldtype": "Link",
				"insert_after": "approvers_section",
				"is_system_generated": 1,
				"label": "Expense Approver",
				"options": "User",
			},
			{
				"fieldname": "approvers_section",
				"fieldtype": "Section Break",
				"hidden": 1,
				"insert_after": "holiday_list",
				"is_system_generated": 1,
				"label": "Approvers",
			},
			{
				"depends_on": "eval:doc.health_insurance_provider",
				"fieldname": "health_insurance_no",
				"fieldtype": "Data",
				"hidden": 1,
				"insert_after": "health_insurance_provider",
				"is_system_generated": 1,
				"label": "Health Insurance No",
				"translatable": 1,
			},
			{
				"collapsible": 1,
				"fieldname": "health_insurance_section",
				"fieldtype": "Section Break",
				"insert_after": "date_of_naturalization",
				"is_system_generated": 1,
				"label": "Health Insurance",
			},
			{
				"fieldname": "grade",
				"fieldtype": "Link",
				"insert_after": "is_in_kuwait",
				"is_system_generated": 1,
				"label": "Grade",
				"options": "Employee Grade",
			},
			{
				"fieldname": "employment_type",
				"fieldtype": "Link",
				"ignore_user_permissions": 1,
				"insert_after": "department_code",
				"is_system_generated": 1,
				"label": "Employment Type",
				"options": "Employment Type",
			},
			{
				"depends_on": "eval:doc.shift_working==0 && !doc.attendance_by_timesheet",
				"fetch_from": "shift.shift_type",
				"fieldname": "default_shift",
				"fieldtype": "Link",
				"insert_after": "project",
				"label": "Default Shift",
				"options": "Shift Type",
				"read_only": 1,
			},
			{
				"fieldname": "government_relation",
				"fieldtype": "Tab Break",
				"insert_after": "reports_to",
				"label": "Government Relation",
			},
			{
				"fieldname": "job_applicant",
				"fieldtype": "Link",
				"insert_after": "job_offer_details",
				"label": "Job Applicant",
				"options": "Job Applicant",
			},
			{
				"fieldname": "column_break_120",
				"fieldtype": "Column Break",
				"insert_after": "bank_account",
			},
			{
				"depends_on": "eval:doc.shift_working==0 && doc.employment_type!=\"Contract\"",
				"fieldname": "checkin_location",
				"fieldtype": "Link",
				"insert_after": "one_fm_provide_accommodation_by_company",
				"is_system_generated": 1,
				"label": "Checkin Location",
				"options": "Location",
				"read_only_depends_on": "",
			},
			{
				"depends_on": "eval:!doc.attendance_by_timesheet",
				"fieldname": "shift_working_html",
				"fieldtype": "HTML",
				"insert_after": "column_break_44",
				"is_system_generated": 1,
				"label": "Shift Working Html",
			},
			{
				"default": "0",
				"fetch_from": "one_fm_erf.number_of_days_off",
				"fetch_if_empty": 1,
				"fieldname": "number_of_days_off",
				"fieldtype": "Int",
				"insert_after": "day_off_category",
				"is_system_generated": 1,
				"label": "Number of Days Off",
				"reqd": 1,
			},
			{
				"default": "Monthly",
				"fetch_from": "one_fm_erf.day_off_category",
				"fetch_if_empty": 1,
				"fieldname": "day_off_category",
				"fieldtype": "Select",
				"insert_after": "leave_policy",
				"is_system_generated": 1,
				"label": "Day Off Category",
				"options": "Monthly\nWeekly",
				"reqd": 1,
				"translatable": 1,
			},
			{
				"depends_on": "eval:!doc.attendance_by_timesheet",
				"fetch_from": "job_offer.operations_shift",
				"fetch_if_empty": 1,
				"fieldname": "shift",
				"fieldtype": "Link",
				"insert_after": "shift_working",
				"is_system_generated": 1,
				"label": "Shift Allocation",
				"mandatory_depends_on": "eval:!doc.attendance_by_timesheet",
				"options": "Operations Shift",
			},
			{
				"depends_on": None,
				"fetch_from": "shift.project",
				"fieldname": "project",
				"fieldtype": "Link",
				"insert_after": "site",
				"is_system_generated": 1,
				"label": "Project Allocation",
				"mandatory_depends_on": "",
				"options": "Project",
				"read_only_depends_on": "shift",
			},
			{
				"depends_on": "eval:!doc.attendance_by_timesheet",
				"fetch_from": "shift.site",
				"fieldname": "site",
				"fieldtype": "Link",
				"insert_after": "shift",
				"is_system_generated": 1,
				"label": "Site Allocation",
				"mandatory_depends_on": "",
				"options": "Operations Site",
				"read_only": 1,
			},
			{
				"default": "1",
				"fetch_from": "one_fm_erf.shift_working",
				"fetch_if_empty": 1,
				"fieldname": "shift_working",
				"fieldtype": "Check",
				"hidden": 1,
				"insert_after": "shift_working_html",
				"is_system_generated": 1,
				"label": "Shift Working",
			},
			{
				"fetch_from": "job_applicant.one_fm_in_kuwait_at_present",
				"fieldname": "is_in_kuwait",
				"fieldtype": "Check",
				"insert_after": "pifss_id_no",
				"is_system_generated": 1,
				"label": "Is in Kuwait?",
			},
			{
				"fieldname": "pifss_id_no",
				"fieldtype": "Data",
				"insert_after": "one_fm_centralized_number",
				"is_system_generated": 1,
				"label": "PIFSS ID No",
				"translatable": 1,
			},
			{
				"fieldname": "one_fm_centralized_number",
				"fieldtype": "Data",
				"insert_after": "civil_id_expiry_date",
				"is_system_generated": 1,
				"label": "Centralized Number",
				"translatable": 1,
			},
			{
				"fieldname": "column_break_72",
				"fieldtype": "Column Break",
				"insert_after": "under_company_residency",
				"is_system_generated": 1,
			},
			{
				"depends_on": "eval:doc.under_company_residency==1",
				"fieldname": "pam_type",
				"fieldtype": "Select",
				"insert_after": "work_permit",
				"is_system_generated": 1,
				"label": "Work Permit Type",
				"options": "\nInside\nOutside\nKuwaiti",
				"translatable": 1,
			},
			{
				"fieldname": "bank_account",
				"fieldtype": "Link",
				"insert_after": "job_offer_salary_structure",
				"is_system_generated": 1,
				"label": "Bank Account",
				"options": "Bank Account",
			},
			{
				"fieldname": "column_break_77",
				"fieldtype": "Column Break",
				"insert_after": "subscription_end_date",
				"is_system_generated": 1,
			},
			{
				"fieldname": "employee_signature",
				"fieldtype": "Signature",
				"insert_after": "health_details",
				"is_system_generated": 1,
				"label": "Employee Signature",
				"read_only": 1,
			},
			{
				"fieldname": "leave_policy",
				"fieldtype": "Link",
				"insert_after": "went_to_hajj",
				"is_system_generated": 1,
				"label": "Leave Policy",
				"options": "Leave Policy",
			},
			{
				"fieldname": "device_os",
				"fieldtype": "Data",
				"hidden": 1,
				"insert_after": "create_user_permission",
				"is_system_generated": 1,
				"label": "Device OS",
				"read_only": 1,
			},
			{
				"collapsible": 1,
				"fieldname": "children_details_section",
				"fieldtype": "Section Break",
				"insert_after": "employee_signature",
				"is_system_generated": 1,
				"label": "Children Details Section",
			},
			{
				"fieldname": "children_details",
				"fieldtype": "Table",
				"insert_after": "number_of_children",
				"is_system_generated": 1,
				"label": "Children Details ",
				"options": "Children Details Table",
			},
			{
				"depends_on": "",
				"fetch_from": "job_applicant.one_fm_number_of_kids",
				"fieldname": "number_of_children",
				"fieldtype": "Data",
				"insert_after": "children_details_section",
				"is_system_generated": 1,
				"label": "Number Of Children",
				"translatable": 1,
				"width": "33"
			},
			{
				"fieldname": "one_fm_forth_name_in_arabic",
				"fieldtype": "Data",
				"insert_after": "one_fm_third_name_in_arabic",
				"is_system_generated": 1,
				"label": "Forth Name in Arabic",
				"translatable": 1,
			},
			{
				"fieldname": "one_fm_forth_name",
				"fieldtype": "Data",
				"insert_after": "one_fm_third_name",
				"is_system_generated": 1,
				"label": "Forth Name",
				"translatable": 1,
			},
			{
				"fieldname": "fcm_token",
				"fieldtype": "Text",
				"hidden": 1,
				"insert_after": "device_os",
				"is_system_generated": 1,
				"label": "FCM Token",
				"read_only": 1,
				"translatable": 1,
			},
			{
				"bold": 1,
				"default": "",
				"fieldname": "one_fm_place_of_birth",
				"fieldtype": "Link",
				"insert_after": "one_fm_religion",
				"is_system_generated": 1,
				"label": "Place Of Birth",
				"options": "Country",
			},
			{
				"fieldname": "one_fm_religion",
				"fieldtype": "Link",
				"insert_after": "blood_group",
				"is_system_generated": 1,
				"label": "Religion",
				"options": "Religion",
			},
			{
				"depends_on": "",
				"fieldname": "under_company_residency",
				"fieldtype": "Check",
				"insert_after": "residency_expiry_date",
				"is_system_generated": 1,
				"label": "Under Company Residency",
			},
			{
				"fieldname": "employee_name_in_arabic",
				"fieldtype": "Data",
				"in_global_search": 1,
				"in_standard_filter": 1,
				"insert_after": "one_fm_last_name_in_arabic",
				"is_system_generated": 1,
				"label": "Full Name in Arabic",
				"read_only": 1,
				"translatable": 1,
			},
			{
				"depends_on": "eval:doc.under_company_residency==1",
				"fieldname": "one_fm_work_permit",
				"fieldtype": "Data",
				"hidden": 1,
				"insert_after": "column_break_72",
				"is_system_generated": 1,
				"label": "Work Permit",
				"translatable": 1,
			},
			{
				"depends_on": "eval:doc.under_company_residency==1",
				"fieldname": "work_permit",
				"fieldtype": "Link",
				"insert_after": "one_fm_work_permit",
				"is_system_generated": 1,
				"label": "Work Permit",
				"options": "Work Permit",
			},
			{
				"fieldname": "civil_id_expiry_date",
				"fieldtype": "Date",
				"insert_after": "one_fm_civil_id",
				"is_system_generated": 1,
				"label": "Civil ID Expiry Date",
			},
			{
				"depends_on": "eval:doc.under_company_residency==1",
				"fieldname": "work_permit_salary",
				"fieldtype": "Currency",
				"insert_after": "custom_employee_image",
				"is_system_generated": 1,
				"label": "Work Permit Salary",
			},
			{
				"depends_on": "eval:doc.under_company_residency==1",
				"fieldname": "work_permit_expiry_date",
				"fieldtype": "Date",
				"insert_after": "work_permit_salary",
				"is_system_generated": 1,
				"label": "Work Permit Expiry Date",
			},
			{
				"depends_on": "eval:doc.under_company_residency==1",
				"fieldname": "residency_expiry_date",
				"fieldtype": "Date",
				"insert_after": "pam_file_number",
				"is_system_generated": 1,
				"label": "Residency Expiry Date",
				"mandatory_depends_on": "",
			},
			{
				"depends_on": "eval:doc.one_fm_nationality=='Kuwaiti'",
				"fieldname": "date_of_naturalization",
				"fieldtype": "Date",
				"insert_after": "nationality_cb",
				"is_system_generated": 1,
				"label": "Date of Naturalization",
			},
			{
				"fieldname": "nationality_cb",
				"fieldtype": "Column Break",
				"insert_after": "nationality_subject",
				"is_system_generated": 1,
				"label": "",
			},
			{
				"depends_on": "eval:doc.one_fm_nationality=='Kuwaiti'",
				"fieldname": "nationality_subject",
				"fieldtype": "Select",
				"insert_after": "nationality_no",
				"is_system_generated": 1,
				"label": "Nationality Subject",
				"options": "\n\u0627\u0644\u0623\u0648\u0644\u064a\n\u0627\u0644\u062b\u0627\u0646\u064a\u0629\n\u0627\u0644\u062b\u0627\u0644\u062b\u0629\n\u0627\u0644\u0631\u0627\u0628\u0639\u0629\n\u0627\u0644\u062e\u0627\u0645\u0633\u0629\n\u0627\u0644\u0633\u0627\u0628\u0639\u0629\n\u0627\u0644\u062b\u0627\u0645\u0646\u0629",
				"translatable": 1,
			},
			{
				"depends_on": "eval:doc.one_fm_nationality=='Kuwaiti'",
				"fieldname": "nationality_no",
				"fieldtype": "Data",
				"insert_after": "nationality_details_section",
				"is_system_generated": 1,
				"label": "Nationality No",
				"translatable": 1,
			},
			{
				"collapsible": 1,
				"depends_on": "eval:doc.one_fm_nationality=='Kuwaiti'",
				"fieldname": "nationality_details_section",
				"fieldtype": "Section Break",
				"insert_after": "children_details",
				"is_system_generated": 1,
				"label": "Nationality Details",
			},
			{
				"fetch_from": "job_offer.one_fm_salary_structure",
				"fieldname": "job_offer_salary_structure",
				"fieldtype": "Link",
				"hidden": 1,
				"insert_after": "job_offer",
				"is_system_generated": 1,
				"label": "Job Offer Salary Structure",
				"options": "Salary Structure",
				"read_only": 1,
			},
			{
				"fieldname": "job_offer",
				"fieldtype": "Link",
				"insert_after": "job_applicant",
				"is_system_generated": 1,
				"label": "Job Offer",
				"options": "Job Offer",
				"read_only": 1,
			},
			{
				"fieldname": "job_offer_details",
				"fieldtype": "Section Break",
				"insert_after": "enrolled",
				"is_system_generated": 1,
				"label": "Job Offer Details",
			},
			{
				"depends_on": "one_fm_provide_accommodation_by_company",
				"fieldname": "one_fm_accommodation_policy",
				"fieldtype": "Attach",
				"insert_after": "date_of_retirement",
				"is_system_generated": 1,
				"label": "Accommodation Policy",
			},
			{
				"fieldname": "subscription_end_date",
				"fieldtype": "Date",
				"insert_after": "subscription_start_date",
				"is_system_generated": 1,
				"label": "Subscription End Date",
				"read_only": 1,
			},
			{
				"fieldname": "subscription_start_date",
				"fieldtype": "Date",
				"insert_after": "old_parent",
				"is_system_generated": 1,
				"label": "Subscription Start Date",
				"read_only": 1,
			},
			{
				"depends_on": "",
				"fieldname": "column_break_64",
				"fieldtype": "Column Break",
				"insert_after": "work_permit_expiry_date",
				"is_system_generated": 1,
			},
			{
				"collapsible": 1,
				"fieldname": "government_relations",
				"fieldtype": "Section Break",
				"insert_after": "government_relation",
				"is_system_generated": 1,
				"label": "",
			},
			{
				"fieldname": "one_fm_provide_accommodation_by_company",
				"fieldtype": "Check",
				"insert_after": "one_fm_erf",
				"is_system_generated": 1,
				"label": "Provide Accommodation by Company",
			},
			{
				"fetch_from": "job_applicant.one_fm_erf",
				"fetch_if_empty": 1,
				"fieldname": "one_fm_erf",
				"fieldtype": "Link",
				"insert_after": "connections_tab",
				"is_system_generated": 1,
				"label": "ERF",
				"options": "ERF",
				"read_only": 1,
			},
			{
				"default": "0.0",
				"fieldname": "annual_leave_balance",
				"fieldtype": "Float",
				"insert_after": "attendance_device_id",
				"is_system_generated": 1,
				"label": "Annual Leave Balance",
				"reqd": 1,
			},
			{
				"depends_on": "",
				"fieldname": "one_fm_last_name_in_arabic",
				"fieldtype": "Data",
				"insert_after": "one_fm_forth_name_in_arabic",
				"is_system_generated": 1,
				"label": "Last Name in Arabic",
				"reqd": 1,
				"translatable": 1,
			},
			{
				"depends_on": "",
				"fieldname": "one_fm_third_name_in_arabic",
				"fieldtype": "Data",
				"insert_after": "one_fm_second_name_in_arabic",
				"is_system_generated": 1,
				"label": "Third Name in Arabic",
				"translatable": 1,
			},
			{
				"depends_on": "",
				"fieldname": "one_fm_second_name_in_arabic",
				"fieldtype": "Data",
				"insert_after": "one_fm_first_name_in_arabic",
				"is_system_generated": 1,
				"label": "Second Name in Arabic",
				"translatable": 1,
			},
			{
				"depends_on": "",
				"fieldname": "one_fm_first_name_in_arabic",
				"fieldtype": "Data",
				"insert_after": "column_break_9",
				"is_system_generated": 1,
				"label": "First Name in Arabic",
				"reqd": 1,
				"translatable": 1,
			},
			{
				"collapsible": 1,
				"fieldname": "one_fm_employee_documents_section",
				"fieldtype": "Section Break",
				"insert_after": "one_fm_handover_asset",
				"is_system_generated": 1,
				"label": "Employee Documents",
			},
			{
				"fieldname": "one_fm_employee_documents",
				"fieldtype": "Table",
				"insert_after": "one_fm_employee_documents_section",
				"is_system_generated": 1,
				"label": "",
				"options": "Employee Document",
			},
			{
				"fieldname": "one_fm_duration_of_work_permit",
				"fieldtype": "Float",
				"insert_after": "one_fm_date_of_entry_in_kuwait",
				"is_system_generated": 1,
				"label": "Duration of Work Permit (in Years)",
			},
			{
				"fieldname": "one_fm_date_of_entry_in_kuwait",
				"fieldtype": "Date",
				"insert_after": "one_fm_date_of_issuance_of_visa",
				"is_system_generated": 1,
				"label": "Date of Entry in Kuwait",
			},
			{
				"fieldname": "one_fm_date_of_issuance_of_visa",
				"fieldtype": "Date",
				"insert_after": "one_fm_visa_reference_number",
				"is_system_generated": 1,
				"label": "Date of issuance of Visa",
			},
			{
				"fieldname": "one_fm_visa_reference_number",
				"fieldtype": "Data",
				"insert_after": "final_confirmation_date",
				"is_system_generated": 1,
				"label": "Visa Reference Number",
				"translatable": 1,
			},
			{
				"fieldname": "one_fm_civil_id",
				"fieldtype": "Data",
				"insert_after": "column_break_64",
				"is_system_generated": 1,
				"label": "CIVIL ID",
				"translatable": 1,
			},
			{
				"depends_on": "eval:doc.under_company_residency==1",
				"fieldname": "one_fm_pam_designation",
				"fieldtype": "Link",
				"insert_after": "government_relations",
				"is_system_generated": 1,
				"label": "PAM Designation",
				"mandatory_depends_on": "work_permit",
				"options": "PAM Designation List",
			},
			{
				"fieldname": "one_fm_basic_salary",
				"fieldtype": "Currency",
				"insert_after": "one_fm_salary_type",
				"is_system_generated": 1,
				"label": "Base Salary",
				"reqd": 1,
			},
			{
				"default": "Monthly",
				"fetch_from": "job_offer_salary_structure.",
				"fetch_if_empty": 1,
				"fieldname": "one_fm_salary_type",
				"fieldtype": "Select",
				"insert_after": "bank_ac_no",
				"is_system_generated": 1,
				"label": "Salary Type",
				"options": "\nMonthly\nWeekly\nDaily",
				"translatable": 1,
			},
			{
				"fieldname": "one_fm__highest_educational_qualification",
				"fieldtype": "Select",
				"insert_after": "education",
				"is_system_generated": 1,
				"label": "Highest Educational Qualification",
				"options": "\nPost Graduate\nMasters\nGraduate\nDiploma\nUnder Graduate\nHigh School",
				"translatable": 1,
			},
			{
				"fieldname": "one_fm_passport_type",
				"fieldtype": "Select",
				"insert_after": "one_fm_nationality",
				"is_system_generated": 1,
				"label": "Passport Type",
				"options": "\nDiplomat\nNormal",
				"translatable": 1,
			},
			{
				"fieldname": "one_fm_nationality",
				"fieldtype": "Link",
				"insert_after": "personal_details",
				"is_system_generated": 1,
				"label": "Nationality",
				"options": "Nationality",
			},
			{
				"fieldname": "one_fm_third_name",
				"fieldtype": "Data",
				"insert_after": "middle_name",
				"is_system_generated": 1,
				"label": "Third Name",
				"translatable": 1,
			},
			{
				"depends_on": "one_fm_employee_asset",
				"fieldname": "one_fm_handover_asset",
				"fieldtype": "Button",
				"insert_after": "one_fm_employee_asset",
				"is_system_generated": 1,
				"label": "Handover Asset",
			},
			{
				"fieldname": "one_fm_employee_asset",
				"fieldtype": "Table",
				"insert_after": "one_fm_employee_asset_details_section",
				"is_system_generated": 1,
				"label": "Employee Asset",
				"options": "Employee Asset",
				"read_only": 1,
			},
			{
				"collapsible": 1,
				"fieldname": "one_fm_employee_asset_details_section",
				"fieldtype": "Section Break",
				"insert_after": "internal_work_history",
				"is_system_generated": 1,
				"label": "Employee Asset Details",
			},
			{
				"depends_on": "",
				"description": "",
				"fieldname": "enrolled",
				"fieldtype": "Check",
				"insert_after": "checkin_location",
				"is_system_generated": 1,
				"label": "Enrolled with face recognition system for attendance",
				"mandatory_depends_on": "",
				"read_only": 1,
			},
			{
				"fieldname": "signature",
				"fieldtype": "Attach Image",
				"hidden": 1,
				"insert_after": "image",
				"is_system_generated": 1,
				"label": "Signature",
			},
			{
				"allow_on_submit": 1,
				"fieldname": "workflow_state",
				"fieldtype": "Link",
				"hidden": 1,
				"is_system_generated": 1,
				"label": "Workflow State",
				"no_copy": 1,
				"options": "Workflow State",
			},
			{
				"fetch_from": "department.department_code",
				"fieldname": "department_code",
				"fieldtype": "Read Only",
				"insert_after": "coulumn_break_ar2",
				"is_system_generated": 1,
				"label": "Department Code",
			},
			{
				"default": "",
				"fieldname": "went_to_hajj",
				"fieldtype": "Check",
				"insert_after": "annual_leave_balance",
				"is_system_generated": 1,
				"label": "Went to Hajj",
			},
			{
			"fieldname": "site_supervisor_name",
			"fieldtype": "Data",
			"label": "Site Supervisor Name",
			"insert_after": "site",
			"fetch_from":"site.site_supervisor_name",
			"read_only": 1,
			},
			{
			"fieldname": "project_manager_name",
			"fieldtype": "Data",
			"label": "Project Manager Name",
			"insert_after": "project",
			"fetch_from":"project.project_manager_name",
			"read_only": 1,
			},
			{
			"fieldname": "custom_day_off_preference",
			"fieldtype": "Select",
			"label": "Day Off Preference",
			"insert_after": "leave_policy",
			"options": "\nDay Off\nDay Off OT"
			}
		]
	}

