def get_employee_custom_fields():
	return {
		"Employee": [
			{
				"fieldname": "annual_leave_balance",
				"label": "Annual Leave Balance",
				"fieldtype": "Float",
				"insert_after": "attendance_device_id",
				"default": "0.0",
				"reqd": 1,
			},
			{
				"fieldname": "approvers_section",
				"label": "Approvers",
				"fieldtype": "Section Break",
				"insert_after": "holiday_list",
				"hidden": 1,
			},
			{
				"fieldname": "arabic_names",
				"label": "Arabic Names",
				"fieldtype": "Section Break",
				"insert_after": "grade",
				"hidden": 1,
			},
			{
				"fieldname": "attendance_by_timesheet",
				"label": "Attendance by Timesheet",
				"fieldtype": "Check",
				"insert_after": "number_of_days_off",
				"fetch_from": "employment_type.attendance_by_timesheet",
			},
			{
				"fieldname": "auto_attendance",
				"label": "Auto Attendance",
				"fieldtype": "Check",
				"insert_after": "attendance_by_timesheet",
				"read_only": 1,
			},
			{
				"fieldname": "bank_account",
				"label": "Bank Account",
				"fieldtype": "Link",
				"options": "Bank Account",
				"insert_after": "job_offer_salary_structure",
			},
			{
				"fieldname": "checkin_location",
				"label": "Checkin Location",
				"fieldtype": "Link",
				"options": "Location",
				"insert_after": "one_fm_provide_accommodation_by_company",
				"depends_on": "eval:doc.shift_working==0 && doc.employment_type!=\"Contract\"",
			},
			{
				"fieldname": "children_details",
				"label": "Children Details ",
				"fieldtype": "Table",
				"options": "Children Details Table",
				"insert_after": "number_of_children",
			},
			{
				"fieldname": "children_details_section",
				"label": "Children Details Section",
				"fieldtype": "Section Break",
				"insert_after": "employee_signature",
				"collapsible": 1,
			},
			{
				"fieldname": "civil_id_expiry_date",
				"label": "Civil ID Expiry Date",
				"fieldtype": "Date",
				"insert_after": "one_fm_civil_id",
			},
			{
				"fieldname": "column_break_120",
				"fieldtype": "Column Break",
				"insert_after": "bank_account",
			},
			{
				"fieldname": "column_break_45",
				"fieldtype": "Column Break",
				"insert_after": "leave_approver",
			},
			{
				"fieldname": "column_break_64",
				"fieldtype": "Column Break",
				"insert_after": "work_permit_expiry_date",
			},
			{
				"fieldname": "column_break_72",
				"fieldtype": "Column Break",
				"insert_after": "under_company_residency",
			},
			{
				"fieldname": "column_break_77",
				"fieldtype": "Column Break",
				"insert_after": "subscription_end_date",
			},
			{
				"fieldname": "column_break_after_bank_name",
				"fieldtype": "Column Break",
				"insert_after": "bank_name",
			},
			{
				"fieldname": "column_break_ar1",
				"fieldtype": "Column Break",
				"insert_after": "branch",
				"hidden": 1,
			},
			{
				"fieldname": "column_break_heye",
				"fieldtype": "Column Break",
				"insert_after": "column_break_after_bank_name",
			},
			{
				"fieldname": "coulumn_break_ar2",
				"fieldtype": "Column Break",
				"insert_after": "department",
			},
			{
				"fieldname": "current_resignation",
				"label": "Current Resignation",
				"fieldtype": "Link",
				"options": "Employee Resignation",
				"insert_after": "resignation_status",
				"read_only": 1,
				"hidden": 1,
			},
			{
				"fieldname": "current_withdrawal",
				"label": "Current Withdrawal",
				"fieldtype": "Link",
				"options": "Employee Resignation Withdrawal",
				"insert_after": "current_resignation",
			},
			{
				"fieldname": "custom_civil_id_assurance_level",
				"label": "Civil ID Assurance Level",
				"fieldtype": "Data",
				"insert_after": "one_fm_centralized_number",
				"read_only": 1,
				"translatable": 1,
			},
			{
				"fieldname": "custom_day_off_preference",
				"label": "Day Off Preference",
				"fieldtype": "Select",
				"options": "\nDay Off\nDay Off OT",
				"insert_after": "leave_policy",
				"translatable": 1,
			},
			{
				"fieldname": "custom_employee_image",
				"label": "Employee Image",
				"fieldtype": "Image",
				"options": "custom_employee_photo",
				"insert_after": "work_permit",
			},
			{
				"fieldname": "custom_employee_photo",
				"label": "Employee Photo",
				"fieldtype": "Attach Image",
				"insert_after": "under_company_residency",
			},
			{
				"fieldname": "custom_enable_face_recognition",
				"label": "Enable Face Recognition",
				"fieldtype": "Check",
				"insert_after": "checkin_location",
			},
			{
				"fieldname": "custom_is_rambo_reliever",
				"label": "Is Rambo Reliever",
				"fieldtype": "Check",
				"insert_after": "custom_is_weekend_reliever",
				"depends_on": "eval:!doc.attendance_by_timesheet",
				"description": "If checked, the Employee is categorized as a Rambo reliever in Roster.",
			},
			{
				"fieldname": "custom_is_reliever",
				"label": "Is Day Off Reliever",
				"fieldtype": "Check",
				"insert_after": "shift_working",
				"depends_on": "eval:!doc.attendance_by_timesheet",
				"description": "If checked, the Employee can be selected as day off reliever in Roster.",
			},
			{
				"fieldname": "custom_is_weekend_reliever",
				"label": "Is Weekend Reliever",
				"fieldtype": "Check",
				"insert_after": "custom_is_reliever",
				"depends_on": "eval:!doc.attendance_by_timesheet",
				"description": "If checked, the Employee can be selected as weekend reliever in Roster.",
			},
			{
				"fieldname": "custom_occupational_sector",
				"label": "Occupational Sector",
				"fieldtype": "Data",
				"insert_after": "one_fm_pam_designation",
				"depends_on": "eval:doc.under_company_residency==1",
				"fetch_from": "one_fm_pam_designation.occupational_sector",
				"translatable": 1,
			},
			{
				"fieldname": "custom_operations_role_allocation",
				"label": "Operations Role Allocation",
				"fieldtype": "Link",
				"options": "Operations Role",
				"insert_after": "shift",
				"depends_on": "eval:doc.shift",
				"mandatory_depends_on": "eval:doc.shift&&doc.shift_working&&!doc.custom_is_reliever",
			},
			{
				"fieldname": "custom_payroll_cycle_end_date",
				"label": "Payroll Cycle End Date",
				"fieldtype": "Data",
				"insert_after": "custom_payroll_cycle_start_date",
				"fetch_from": "project.custom_payroll_end_date",
				"translatable": 1,
			},
			{
				"fieldname": "custom_payroll_cycle_start_date",
				"label": "Payroll Cycle Start Date",
				"fieldtype": "Data",
				"insert_after": "payroll_cost_center",
				"fetch_from": "project.custom_payroll_start_date",
				"fetch_if_empty": 1,
				"read_only": 1,
				"ignore_user_permissions": 1,
				"translatable": 1,
			},
			{
				"fieldname": "custom_site_supervisor",
				"label": "Site Supervisor",
				"fieldtype": "Link",
				"options": "Employee",
				"insert_after": "site",
				"fetch_from": "site.site_supervisor",
				"read_only": 1,
			},
			{
				"fieldname": "custom_site_supervisor_user",
				"label": "Site Supervisor User",
				"fieldtype": "Link",
				"options": "User",
				"insert_after": "site_supervisor_name",
				"fetch_from": "custom_site_supervisor.user_id",
				"description": "The User of the site supervisor on this employee's Operations Site. Set automatically.",
				"read_only": 1,
			},
			{
				"fieldname": "custom_subcontractor_name",
				"label": "Subcontractor Name",
				"fieldtype": "Link",
				"options": "Supplier",
				"insert_after": "employee_number",
				"depends_on": "eval:doc.employment_type == \"Subcontractor\"",
			},
			{
				"fieldname": "date_of_naturalization",
				"label": "Date of Naturalization",
				"fieldtype": "Date",
				"insert_after": "nationality_cb",
				"depends_on": "eval:doc.one_fm_nationality=='Kuwaiti'",
			},
			{
				"fieldname": "day_off_category",
				"label": "Day Off Category",
				"fieldtype": "Select",
				"options": "Monthly\nWeekly",
				"insert_after": "leave_policy",
				"fetch_from": "one_fm_erf.day_off_category",
				"fetch_if_empty": 1,
				"default": "Monthly",
				"reqd": 1,
				"translatable": 1,
			},
			{
				"fieldname": "default_shift",
				"label": "Default Shift",
				"fieldtype": "Link",
				"options": "Shift Type",
				"insert_after": "project",
				"depends_on": "eval:doc.shift_working==0 && !doc.attendance_by_timesheet",
				"fetch_from": "shift.shift_type",
				"read_only": 1,
			},
			{
				"fieldname": "department_code",
				"label": "Department Code",
				"fieldtype": "Read Only",
				"insert_after": "coulumn_break_ar2",
				"fetch_from": "department.department_code",
			},
			{
				"fieldname": "device_os",
				"label": "Device OS",
				"fieldtype": "Data",
				"insert_after": "create_user_permission",
				"read_only": 1,
				"hidden": 1,
			},
			{
				"fieldname": "employee_id",
				"label": "Employee ID",
				"fieldtype": "Data",
				"insert_after": "status",
				"read_only": 1,
				"unique": 1,
				"in_list_view": 1,
				"in_standard_filter": 1,
			},
			{
				"fieldname": "employee_name_in_arabic",
				"label": "Full Name in Arabic",
				"fieldtype": "Data",
				"insert_after": "one_fm_last_name_in_arabic",
				"read_only": 1,
				"in_standard_filter": 1,
				"in_global_search": 1,
				"translatable": 1,
			},
			{
				"fieldname": "employee_signature",
				"label": "Employee Signature",
				"fieldtype": "Signature",
				"insert_after": "health_details",
				"read_only": 1,
			},
			{
				"fieldname": "employment_type",
				"label": "Employment Type",
				"fieldtype": "Link",
				"options": "Employment Type",
				"insert_after": "department_code",
				"ignore_user_permissions": 1,
			},
			{
				"fieldname": "enrolled",
				"label": "Enrolled with face recognition system for attendance",
				"fieldtype": "Check",
				"insert_after": "checkin_location",
				"read_only": 1,
			},
			{
				"fieldname": "expense_approver",
				"label": "Expense Approver",
				"fieldtype": "Link",
				"options": "User",
				"insert_after": "approvers_section",
			},
			{
				"fieldname": "fcm_token",
				"label": "FCM Token",
				"fieldtype": "Text",
				"insert_after": "device_os",
				"read_only": 1,
				"hidden": 1,
				"translatable": 1,
			},
			{
				"fieldname": "government_relation",
				"label": "Government Relation",
				"fieldtype": "Tab Break",
				"insert_after": "reports_to",
			},
			{
				"fieldname": "government_relations",
				"fieldtype": "Section Break",
				"insert_after": "government_relation",
				"collapsible": 1,
			},
			{
				"fieldname": "grade",
				"label": "Grade",
				"fieldtype": "Link",
				"options": "Employee Grade",
				"insert_after": "is_in_kuwait",
			},
			{
				"fieldname": "health_insurance_no",
				"label": "Health Insurance No",
				"fieldtype": "Data",
				"insert_after": "health_insurance_provider",
				"depends_on": "eval:doc.health_insurance_provider",
				"hidden": 1,
				"translatable": 1,
			},
			{
				"fieldname": "health_insurance_provider",
				"label": "Health Insurance Provider",
				"fieldtype": "Table",
				"options": "Health Insurance Provider Detail",
				"insert_after": "health_insurance_section",
			},
			{
				"fieldname": "health_insurance_section",
				"label": "Health Insurance",
				"fieldtype": "Section Break",
				"insert_after": "date_of_naturalization",
				"collapsible": 1,
			},
			{
				"fieldname": "iban",
				"label": "IBAN",
				"fieldtype": "Data",
				"insert_after": "one_fm_basic_salary",
				"translatable": 1,
			},
			{
				"fieldname": "is_in_kuwait",
				"label": "Is in Kuwait?",
				"fieldtype": "Check",
				"insert_after": "pifss_id_no",
				"fetch_from": "job_applicant.one_fm_in_kuwait_at_present",
			},
			{
				"fieldname": "is_in_ows",
				"label": "Is in OWS",
				"fieldtype": "Select",
				"options": "\nYes\nNo",
				"insert_after": "employee_id",
				"translatable": 1,
			},
			{
				"fieldname": "job_applicant",
				"label": "Job Applicant",
				"fieldtype": "Link",
				"options": "Job Applicant",
				"insert_after": "job_offer_details",
			},
			{
				"fieldname": "job_offer",
				"label": "Job Offer",
				"fieldtype": "Link",
				"options": "Job Offer",
				"insert_after": "job_applicant",
				"read_only": 1,
			},
			{
				"fieldname": "job_offer_details",
				"label": "Job Offer Details",
				"fieldtype": "Section Break",
				"insert_after": "enrolled",
			},
			{
				"fieldname": "job_offer_salary_structure",
				"label": "Job Offer Salary Structure",
				"fieldtype": "Link",
				"options": "Salary Structure",
				"insert_after": "job_offer",
				"fetch_from": "job_offer.one_fm_salary_structure",
				"read_only": 1,
				"hidden": 1,
			},
			{
				"fieldname": "leave_approver",
				"label": "Leave Approver",
				"fieldtype": "Link",
				"options": "User",
				"insert_after": "expense_approver",
			},
			{
				"fieldname": "leave_policy",
				"label": "Leave Policy",
				"fieldtype": "Link",
				"options": "Leave Policy",
				"insert_after": "went_to_hajj",
			},
			{
				"fieldname": "nationality_cb",
				"fieldtype": "Column Break",
				"insert_after": "nationality_subject",
			},
			{
				"fieldname": "nationality_details_section",
				"label": "Nationality Details",
				"fieldtype": "Section Break",
				"insert_after": "children_details",
				"depends_on": "eval:doc.one_fm_nationality=='Kuwaiti'",
				"collapsible": 1,
				"collapsible_depends_on": "eval:doc.one_fm_nationality=='Kuwaiti'",
			},
			{
				"fieldname": "nationality_no",
				"label": "Nationality No",
				"fieldtype": "Data",
				"insert_after": "nationality_details_section",
				"depends_on": "eval:doc.one_fm_nationality=='Kuwaiti'",
				"translatable": 1,
			},
			{
				"fieldname": "nationality_subject",
				"label": "Nationality Subject",
				"fieldtype": "Select",
				"options": "\nالأولي\nالثانية\nالثالثة\nالرابعة\nالخامسة\nالسابعة\nالثامنة",
				"insert_after": "nationality_no",
				"depends_on": "eval:doc.one_fm_nationality=='Kuwaiti'",
				"translatable": 1,
			},
			{
				"fieldname": "non_kuwaiti_residents",
				"label": "Non Kuwaiti Resident",
				"fieldtype": "Check",
				"insert_after": "auto_attendance",
				"hidden": 1,
			},
			{
				"fieldname": "number_of_children",
				"label": "Number Of Children",
				"fieldtype": "Data",
				"insert_after": "children_details_section",
				"fetch_from": "job_applicant.one_fm_number_of_kids",
				"translatable": 1,
				"width": "33",
			},
			{
				"fieldname": "number_of_days_off",
				"label": "Number of Days Off",
				"fieldtype": "Int",
				"insert_after": "day_off_category",
				"fetch_from": "one_fm_erf.number_of_days_off",
				"fetch_if_empty": 1,
				"default": "0",
				"reqd": 1,
			},
			{
				"fieldname": "one_fm__highest_educational_qualification",
				"label": "Highest Educational Qualification",
				"fieldtype": "Select",
				"options": "\nPost Graduate\nMasters\nGraduate\nDiploma\nUnder Graduate\nHigh School",
				"insert_after": "education",
				"translatable": 1,
			},
			{
				"fieldname": "one_fm_accommodation_policy",
				"label": "Accommodation Policy",
				"fieldtype": "Attach",
				"insert_after": "date_of_retirement",
				"depends_on": "one_fm_provide_accommodation_by_company",
			},
			{
				"fieldname": "one_fm_basic_salary",
				"label": "Base Salary",
				"fieldtype": "Currency",
				"insert_after": "one_fm_salary_type",
				"reqd": 1,
			},
			{
				"fieldname": "one_fm_centralized_number",
				"label": "Centralized Number",
				"fieldtype": "Data",
				"insert_after": "civil_id_expiry_date",
				"translatable": 1,
			},
			{
				"fieldname": "one_fm_civil_id",
				"label": "CIVIL ID",
				"fieldtype": "Data",
				"insert_after": "column_break_64",
				"translatable": 1,
			},
			{
				"fieldname": "one_fm_date_of_entry_in_kuwait",
				"label": "Date of Entry in Kuwait",
				"fieldtype": "Date",
				"insert_after": "one_fm_date_of_issuance_of_visa",
			},
			{
				"fieldname": "one_fm_date_of_issuance_of_visa",
				"label": "Date of Visa Expiry",
				"fieldtype": "Date",
				"insert_after": "one_fm_visa_reference_number",
			},
			{
				"fieldname": "one_fm_duration_of_work_permit",
				"label": "Duration of Work Permit (in Years)",
				"fieldtype": "Float",
				"insert_after": "one_fm_date_of_entry_in_kuwait",
			},
			{
				"fieldname": "one_fm_employee_asset",
				"label": "Employee Asset",
				"fieldtype": "Table",
				"options": "Employee Asset",
				"insert_after": "one_fm_employee_asset_details_section",
				"read_only": 1,
			},
			{
				"fieldname": "one_fm_employee_asset_details_section",
				"label": "Employee Asset Details",
				"fieldtype": "Section Break",
				"insert_after": "internal_work_history",
				"collapsible": 1,
			},
			{
				"fieldname": "one_fm_employee_documents",
				"fieldtype": "Table",
				"options": "Employee Document",
				"insert_after": "one_fm_employee_documents_section",
			},
			{
				"fieldname": "one_fm_employee_documents_section",
				"label": "Employee Documents",
				"fieldtype": "Section Break",
				"insert_after": "one_fm_handover_asset",
				"collapsible": 1,
			},
			{
				"fieldname": "one_fm_erf",
				"label": "ERF",
				"fieldtype": "Link",
				"options": "ERF",
				"insert_after": "connections_tab",
				"fetch_from": "job_applicant.one_fm_erf",
				"fetch_if_empty": 1,
				"read_only": 1,
			},
			{
				"fieldname": "one_fm_first_name_in_arabic",
				"label": "First Name in Arabic",
				"fieldtype": "Data",
				"insert_after": "column_break_9",
				"reqd": 1,
				"translatable": 1,
			},
			{
				"fieldname": "one_fm_fourth_name",
				"label": "Fourth Name",
				"fieldtype": "Data",
				"insert_after": "one_fm_third_name",
				"translatable": 1,
			},
			{
				"fieldname": "one_fm_fourth_name_in_arabic",
				"label": "Fourth Name in Arabic",
				"fieldtype": "Data",
				"insert_after": "one_fm_third_name_in_arabic",
				"translatable": 1,
			},
			{
				"fieldname": "one_fm_handover_asset",
				"label": "Handover Asset",
				"fieldtype": "Button",
				"insert_after": "one_fm_employee_asset",
				"depends_on": "one_fm_employee_asset",
			},
			{
				"fieldname": "one_fm_last_name_in_arabic",
				"label": "Last Name in Arabic",
				"fieldtype": "Data",
				"insert_after": "one_fm_forth_name_in_arabic",
				"reqd": 1,
				"translatable": 1,
			},
			{
				"fieldname": "one_fm_nationality",
				"label": "Nationality",
				"fieldtype": "Link",
				"options": "Nationality",
				"insert_after": "personal_details",
			},
			{
				"fieldname": "one_fm_pam_designation",
				"label": "PAM Designation",
				"fieldtype": "Link",
				"options": "PAM Designation List",
				"insert_after": "government_relations",
				"depends_on": "eval:doc.under_company_residency==1",
				"mandatory_depends_on": "work_permit",
			},
			{
				"fieldname": "one_fm_passport_type",
				"label": "Passport Type",
				"fieldtype": "Select",
				"options": "\nDiplomat\nNormal",
				"insert_after": "one_fm_nationality",
				"translatable": 1,
			},
			{
				"fieldname": "one_fm_place_of_birth",
				"label": "Place Of Birth",
				"fieldtype": "Link",
				"options": "Country",
				"insert_after": "one_fm_religion",
				"bold": 1,
			},
			{
				"fieldname": "one_fm_provide_accommodation_by_company",
				"label": "Provide Accommodation by Company",
				"fieldtype": "Check",
				"insert_after": "one_fm_erf",
			},
			{
				"fieldname": "one_fm_religion",
				"label": "Religion",
				"fieldtype": "Link",
				"options": "Religion",
				"insert_after": "blood_group",
			},
			{
				"fieldname": "one_fm_salary_type",
				"label": "Salary Type",
				"fieldtype": "Select",
				"options": "\nMonthly\nWeekly\nDaily",
				"insert_after": "bank_ac_no",
				"fetch_from": "job_offer_salary_structure.",
				"fetch_if_empty": 1,
				"default": "Monthly",
				"translatable": 1,
			},
			{
				"fieldname": "one_fm_second_name_in_arabic",
				"label": "Second Name in Arabic",
				"fieldtype": "Data",
				"insert_after": "one_fm_first_name_in_arabic",
				"translatable": 1,
			},
			{
				"fieldname": "one_fm_third_name",
				"label": "Third Name",
				"fieldtype": "Data",
				"insert_after": "middle_name",
				"translatable": 1,
			},
			{
				"fieldname": "one_fm_third_name_in_arabic",
				"label": "Third Name in Arabic",
				"fieldtype": "Data",
				"insert_after": "one_fm_second_name_in_arabic",
				"translatable": 1,
			},
			{
				"fieldname": "one_fm_visa_reference_number",
				"label": "Visa Reference Number",
				"fieldtype": "Data",
				"insert_after": "final_confirmation_date",
				"translatable": 1,
			},
			{
				"fieldname": "pam_file",
				"label": "PAM File",
				"fieldtype": "Link",
				"options": "PAM License Details",
				"insert_after": "one_fm_pam_designation",
				"depends_on": "eval:doc.under_company_residency==1",
			},
			{
				"fieldname": "pam_file_number",
				"label": "PAM FIle Number",
				"fieldtype": "Data",
				"insert_after": "pam_file",
				"depends_on": "eval:doc.under_company_residency==1",
				"fetch_from": "pam_file.civil_id_number_for_licensing",
				"read_only": 1,
				"translatable": 1,
			},
			{
				"fieldname": "payroll_cost_center",
				"label": "Payroll Cost Center",
				"fieldtype": "Link",
				"options": "Cost Center",
				"insert_after": "salary_cb",
				"fetch_from": "department.payroll_cost_center",
				"fetch_if_empty": 1,
				"hidden": 1,
			},
			{
				"fieldname": "pifss_id_no",
				"label": "PIFSS ID No",
				"fieldtype": "Data",
				"insert_after": "one_fm_centralized_number",
				"translatable": 1,
			},
			{
				"fieldname": "project",
				"label": "Project Allocation",
				"fieldtype": "Link",
				"options": "Project",
				"insert_after": "site",
				"read_only_depends_on": "shift",
				"fetch_from": "shift.project",
			},
			{
				"fieldname": "project_manager_name",
				"label": "Project Manager Name",
				"fieldtype": "Data",
				"insert_after": "project",
				"depends_on": "eval: doc.project",
				"fetch_from": "project.project_manager_name",
				"read_only": 1,
			},
			{
				"fieldname": "registered",
				"label": "Registered",
				"fieldtype": "Check",
				"insert_after": "custom_enable_face_recognition",
				"default": "0",
				"read_only": 1,
				"no_copy": 1,
			},
			{
				"fieldname": "residency_expiry_date",
				"label": "Residency Expiry Date",
				"fieldtype": "Date",
				"insert_after": "pam_file_number",
				"depends_on": "eval:doc.under_company_residency==1",
			},
			{
				"fieldname": "resignation_date",
				"label": "Resignation Date",
				"fieldtype": "Date",
				"insert_after": "date_of_joining",
				"read_only": 1,
			},
			{
				"fieldname": "resignation_section",
				"fieldtype": "Section Break",
				"insert_after": "feedback",
			},
			{
				"fieldname": "resignation_status",
				"label": "Resignation Workflow Status",
				"fieldtype": "Data",
				"insert_after": "resignation_section",
				"fetch_from": "current_resignation.workflow_state",
				"read_only": 1,
			},
			{
				"fieldname": "salary_cb",
				"fieldtype": "Column Break",
				"insert_after": "salary_mode",
			},
			{
				"fieldname": "shift",
				"label": "Shift Allocation",
				"fieldtype": "Link",
				"options": "Operations Shift",
				"insert_after": "shift_working",
				"depends_on": "eval:!doc.attendance_by_timesheet",
				"mandatory_depends_on": "eval:!doc.attendance_by_timesheet",
				"fetch_from": "job_offer.operations_shift",
				"fetch_if_empty": 1,
			},
			{
				"fieldname": "shift_request_approver",
				"label": "Shift Request Approver",
				"fieldtype": "Link",
				"options": "User",
				"insert_after": "column_break_45",
			},
			{
				"fieldname": "shift_working",
				"label": "Shift Working",
				"fieldtype": "Check",
				"insert_after": "shift_working_html",
				"fetch_from": "one_fm_erf.shift_working",
				"fetch_if_empty": 1,
				"default": "1",
				"hidden": 1,
			},
			{
				"fieldname": "shift_working_html",
				"label": "Shift Working Html",
				"fieldtype": "HTML",
				"insert_after": "column_break_44",
				"depends_on": "eval:!doc.attendance_by_timesheet",
			},
			{
				"fieldname": "signature",
				"label": "Signature",
				"fieldtype": "Attach Image",
				"insert_after": "image",
				"hidden": 1,
			},
			{
				"fieldname": "site",
				"label": "Site Allocation",
				"fieldtype": "Link",
				"options": "Operations Site",
				"insert_after": "shift",
				"depends_on": "eval:!doc.attendance_by_timesheet",
				"fetch_from": "shift.site",
				"read_only": 1,
			},
			{
				"fieldname": "site_supervisor_name",
				"label": "Site Supervisor Name",
				"fieldtype": "Data",
				"insert_after": "site",
				"depends_on": "eval: doc.site",
				"fetch_from": "site.site_supervisor_name",
				"read_only": 1,
			},
			{
				"fieldname": "subscription_end_date",
				"label": "Subscription End Date",
				"fieldtype": "Date",
				"insert_after": "subscription_start_date",
				"read_only": 1,
			},
			{
				"fieldname": "subscription_start_date",
				"label": "Subscription Start Date",
				"fieldtype": "Date",
				"insert_after": "old_parent",
				"read_only": 1,
			},
			{
				"fieldname": "under_company_residency",
				"label": "Under Company Residency",
				"fieldtype": "Check",
				"insert_after": "residency_expiry_date",
			},
			{
				"fieldname": "went_to_hajj",
				"label": "Went to Hajj",
				"fieldtype": "Check",
				"insert_after": "annual_leave_balance",
			},
			{
				"fieldname": "work_permit",
				"label": "Work Permit",
				"fieldtype": "Link",
				"options": "Work Permit",
				"insert_after": "column_break_72",
				"depends_on": "eval:doc.under_company_residency==1",
			},
			{
				"fieldname": "work_permit_expiry_date",
				"label": "Work Permit Expiry Date",
				"fieldtype": "Date",
				"insert_after": "work_permit_salary",
				"depends_on": "eval:doc.under_company_residency==1",
			},
			{
				"fieldname": "work_permit_salary",
				"label": "Work Permit Salary",
				"fieldtype": "Currency",
				"insert_after": "custom_employee_image",
				"depends_on": "eval:doc.under_company_residency==1",
			},
			{
				"fieldname": "workflow_state",
				"label": "Workflow State",
				"fieldtype": "Link",
				"options": "Workflow State",
				"hidden": 1,
				"allow_on_submit": 1,
				"no_copy": 1,
			},
		],
	}
