def get_hd_ticket_custom_fields():
	return {
		"HD Ticket": [
			{
				"fieldname": "column_break_banio",
				"fieldtype": "Column Break",
				"insert_after": "developer_feedback",
			},
			{
				"fieldname": "custom_bug_buster",
				"label": "Bug Buster",
				"fieldtype": "Link",
				"options": "User",
				"insert_after": "ticket_split_from",
				"depends_on": "eval: doc.ticket_type == 'Bug'",
			},
			{
				"fieldname": "custom_dev_ticket",
				"label": "Dev Ticket",
				"fieldtype": "Data",
				"insert_after": "email_account",
				"read_only": 1,
				"translatable": 1,
			},
			{
				"fieldname": "custom_external_customer",
				"label": "Customer",
				"fieldtype": "Link",
				"options": "Customer",
				"insert_after": "custom_project",
				"depends_on": "custom_is_external",
				"fetch_from": "custom_project.customer",
			},
			{
				"fieldname": "custom_github_issue_url",
				"label": "GitHub Issue",
				"fieldtype": "Data",
				"insert_after": "custom_dev_ticket",
				"read_only": 1,
			},
			{
				"fieldname": "custom_is_external",
				"label": "Is External",
				"fieldtype": "Check",
				"insert_after": "subject",
			},
			{
				"fieldname": "custom_pivotal_tracker",
				"label": "Pivotal Tracker",
				"fieldtype": "Data",
				"insert_after": "custom_github_issue_url",
				"read_only": 1,
				"hidden": 1,
				"translatable": 1,
			},
			{
				"fieldname": "custom_process",
				"label": "Process",
				"fieldtype": "Link",
				"options": "Process",
				"insert_after": "custom_reference_doctype",
				"depends_on": "eval: doc.custom_ticket_category == \"Process Issue\" || doc.custom_ticket_category == \"Doctype Issue\"",
				"mandatory_depends_on": "eval: doc.custom_ticket_category == \"Process Issue\"",
				"read_only_depends_on": "eval: doc.custom_ticket_category != \"Process Issue\"",
				"default": "Others",
			},
			{
				"fieldname": "custom_process_owner",
				"label": "Process Owner",
				"fieldtype": "Link",
				"options": "User",
				"insert_after": "custom_process",
				"fetch_from": "custom_process.process_owner",
				"read_only": 1,
				"in_list_view": 1,
				"ignore_user_permissions": 1,
			},
			{
				"fieldname": "custom_project",
				"label": "Project",
				"fieldtype": "Link",
				"options": "Project",
				"insert_after": "custom_is_external",
				"depends_on": "custom_is_external",
				"mandatory_depends_on": "custom_is_external",
			},
			{
				"fieldname": "custom_project_manager",
				"label": "Project Manager",
				"fieldtype": "Link",
				"options": "Employee",
				"insert_after": "custom_external_customer",
				"fetch_from": "custom_project.project_manager",
			},
			{
				"fieldname": "custom_project_manager_name",
				"label": "Project Manager Name",
				"fieldtype": "Data",
				"insert_after": "custom_project_manager",
				"fetch_from": "custom_project.project_manager_name",
				"translatable": 1,
			},
			{
				"fieldname": "custom_reference_doctype",
				"label": "Reference Doctype",
				"fieldtype": "Link",
				"options": "DocType",
				"insert_after": "custom_ticket_category",
				"depends_on": "eval: doc.custom_ticket_category == \"Doctype Issue\"",
				"mandatory_depends_on": "eval: doc.custom_ticket_category == \"Doctype Issue\"",
			},
			{
				"fieldname": "custom_sub_contractor_dispatch_time",
				"label": "Sub Contractor Dispatch Time",
				"fieldtype": "Datetime",
				"insert_after": "custom_time_of_call",
			},
			{
				"fieldname": "custom_ticket_category",
				"label": "Ticket Category",
				"fieldtype": "Select",
				"options": "\nProcess Issue\nDoctype Issue\nFront End Issue\nMobile Issue\nOther Issues",
				"insert_after": "cb00",
				"description": "Categorize the ticket. Selecting \"Process Issue\" reveals the mandatory Process field; selecting \"Doctype Issue\" reveals the mandatory Reference Doctype field.",
				"reqd": 1,
			},
			{
				"fieldname": "custom_time_of_call",
				"label": "Time of Call",
				"fieldtype": "Datetime",
				"insert_after": "resolution_details",
				"depends_on": "eval: doc.custom_is_external",
				"default": "Now",
			},
			{
				"fieldname": "developer_feedback",
				"label": "Developer Feedback",
				"fieldtype": "Small Text",
				"insert_after": "development_feedback_sb",
				"depends_on": "eval:doc.ticket_type=='Bug'",
				"mandatory_depends_on": "eval:doc.ticket_type==\"Bug\" && (doc.status == \"Closed\" || doc.status == \"Resolved\")",
				"translatable": 1,
			},
			{
				"fieldname": "development_feedback_sb",
				"label": "Development Feedback",
				"fieldtype": "Section Break",
				"insert_after": "feedback_extra",
				"collapsible": 1,
			},
			{
				"fieldname": "development_process_owner_remark",
				"label": "Development Process Owner Remark",
				"fieldtype": "Small Text",
				"insert_after": "column_break_banio",
				"depends_on": "eval:doc.ticket_type==\"Bug\" && (doc.status == \"Closed\" || doc.status == \"Resolved\")",
				"translatable": 1,
			},
			{
				"fieldname": "execution_prompt_count",
				"label": "Execution Prompt Count",
				"fieldtype": "Int",
				"insert_after": "planning_prompts_count",
				"depends_on": "eval:doc.ticket_type == 'Bug'",
			},
			{
				"fieldname": "planning_prompts_count",
				"label": "Planning Prompts Count",
				"fieldtype": "Int",
				"insert_after": "resolution_date",
				"depends_on": "eval:doc.ticket_type == 'Bug'",
			},
		],
	}
