def get_job_offer_custom_fields():
	return {
		"Job Offer": [
			{
				"fieldname": "agency",
				"label": "Agency",
				"fieldtype": "Link",
				"options": "Agency",
				"insert_after": "agency_country_process",
				"fetch_from": "job_applicant.one_fm_agency",
				"fetch_if_empty": 1,
				"allow_on_submit": 1,
			},
			{
				"fieldname": "agency_country_process",
				"label": "Agency Country Process",
				"fieldtype": "Link",
				"options": "Agency Country Process",
				"insert_after": "applicant_name",
				"allow_on_submit": 1,
			},
			{
				"fieldname": "attendance_by_timesheet",
				"label": "Attendance by Timesheet",
				"fieldtype": "Check",
				"insert_after": "employment_type",
				"fetch_from": "employment_type.attendance_by_timesheet",
				"read_only": 1,
			},
			{
				"fieldname": "base",
				"label": "Base",
				"fieldtype": "Currency",
				"insert_after": "employee_grade",
			},
			{
				"fieldname": "day_off_category",
				"label": "Day Off Category",
				"fieldtype": "Select",
				"options": "Weekly\nMonthly",
				"insert_after": "onboarding_officer",
				"fetch_from": "one_fm_erf.day_off_category",
				"fetch_if_empty": 1,
				"reqd": 1,
				"allow_on_submit": 1,
			},
			{
				"fieldname": "default_shift",
				"label": "Default Shift",
				"fieldtype": "Link",
				"options": "Shift Type",
				"insert_after": "operations_shift",
				"depends_on": "eval:!doc.attendance_by_timesheet",
				"fetch_from": "operations_shift.shift_type",
				"fetch_if_empty": 1,
				"read_only": 1,
				"allow_on_submit": 1,
			},
			{
				"fieldname": "department",
				"label": "Department",
				"fieldtype": "Link",
				"options": "Department",
				"insert_after": "estimated_date_of_joining",
				"fetch_from": "job_applicant.department",
				"fetch_if_empty": 1,
			},
			{
				"fieldname": "employee_grade",
				"label": "Employee Grade",
				"fieldtype": "Link",
				"options": "Employee Grade",
				"insert_after": "one_fm_salary_details_section",
				"fetch_from": "one_fm_erf.grade",
				"fetch_if_empty": 1,
			},
			{
				"fieldname": "employment_type",
				"label": "Employment Type",
				"fieldtype": "Link",
				"options": "Employment Type",
				"insert_after": "number_of_days_off",
				"fetch_from": "job_applicant.employment_type",
				"fetch_if_empty": 1,
				"reqd": 1,
			},
			{
				"fieldname": "estimated_date_of_joining",
				"label": "Estimated Date of Joining",
				"fieldtype": "Date",
				"insert_after": "one_fm_offer_accepted_date",
				"allow_on_submit": 1,
			},
			{
				"fieldname": "g2g_fee_amount",
				"label": "G2G Fee Amount",
				"fieldtype": "Currency",
				"insert_after": "is_g2g_fees_needed",
				"depends_on": "is_g2g_fees_needed",
				"allow_on_submit": 1,
			},
			{
				"fieldname": "is_g2g_fees_needed",
				"label": "G2G Fees Needed",
				"fieldtype": "Check",
				"insert_after": "one_fm_notify_finance_department",
				"allow_on_submit": 1,
			},
			{
				"fieldname": "is_residency_fine_needed",
				"label": "Residency Fine Needed",
				"fieldtype": "Check",
				"insert_after": "g2g_fee_amount",
				"allow_on_submit": 1,
			},
			{
				"fieldname": "nationality",
				"label": "Nationality",
				"fieldtype": "Link",
				"options": "Nationality",
				"insert_after": "company",
				"fetch_from": "job_applicant.one_fm_nationality",
				"fetch_if_empty": 1,
			},
			{
				"fieldname": "number_of_days_off",
				"label": "Number of Days Off",
				"fieldtype": "Int",
				"insert_after": "day_off_category",
				"fetch_from": "one_fm_erf.number_of_days_off",
				"fetch_if_empty": 1,
				"reqd": 1,
				"allow_on_submit": 1,
			},
			{
				"fieldname": "onboarding_officer",
				"label": "Onboarding Officer",
				"fieldtype": "Link",
				"options": "User",
				"insert_after": "applicant_email",
				"depends_on": "eval:doc.docstatus == 1",
				"allow_on_submit": 1,
			},
			{
				"fieldname": "one_fm_date_of_birth",
				"label": "Date of Birth",
				"fieldtype": "Date",
				"insert_after": "one_fm_passport_holder_of",
				"fetch_from": "job_applicant.one_fm_date_of_birth",
				"read_only": 1,
			},
			{
				"fieldname": "one_fm_erf",
				"label": "ERF",
				"fieldtype": "Link",
				"options": "ERF",
				"insert_after": "job_applicant",
				"fetch_if_empty": 1,
				"read_only": 1,
				"in_standard_filter": 1,
			},
			{
				"fieldname": "one_fm_job_offer_total_salary",
				"label": "Total Monthly Salary",
				"fieldtype": "Currency",
				"insert_after": "one_fm_salary_details",
				"read_only": 1,
			},
			{
				"fieldname": "one_fm_notified_finance_department",
				"label": "Notified Finance Department",
				"fieldtype": "Check",
				"insert_after": "one_fm_salary_advance_paid",
				"hidden": 1,
			},
			{
				"fieldname": "one_fm_notify_finance_department",
				"label": "Notify Finance Department",
				"fieldtype": "Button",
				"insert_after": "one_fm_notified_finance_department",
				"depends_on": "eval:doc.one_fm_provide_salary_advance==1 && doc.one_fm_salary_advance_amount > 0 && doc.one_fm_notified_finance_department != 1",
			},
			{
				"fieldname": "one_fm_offer_accepted_date",
				"label": "Offer Accepted Date",
				"fieldtype": "Date",
				"insert_after": "offer_date",
				"depends_on": "eval:doc.status=='Accepted'",
				"read_only": 1,
				"allow_on_submit": 1,
			},
			{
				"fieldname": "one_fm_passport_column_break",
				"fieldtype": "Column Break",
				"insert_after": "one_fm_date_of_birth",
			},
			{
				"fieldname": "one_fm_passport_details_section",
				"label": "Passport & Date of Birth",
				"fieldtype": "Section Break",
				"insert_after": "residency_fine_amount",
			},
			{
				"fieldname": "one_fm_passport_expire",
				"label": "Passport Expires On",
				"fieldtype": "Date",
				"insert_after": "one_fm_passport_issued",
				"fetch_from": "job_applicant.one_fm_passport_expire",
				"read_only": 1,
			},
			{
				"fieldname": "one_fm_passport_holder_of",
				"label": "Passport Holder Of",
				"fieldtype": "Link",
				"options": "Country",
				"insert_after": "one_fm_passport_number",
				"fetch_from": "job_applicant.one_fm_passport_holder_of",
				"read_only": 1,
			},
			{
				"fieldname": "one_fm_passport_issued",
				"label": "Passport Issued On",
				"fieldtype": "Date",
				"insert_after": "one_fm_passport_column_break",
				"fetch_from": "job_applicant.one_fm_passport_issued",
				"read_only": 1,
			},
			{
				"fieldname": "one_fm_passport_number",
				"label": "Passport Number",
				"fieldtype": "Data",
				"insert_after": "one_fm_passport_details_section",
				"fetch_from": "job_applicant.one_fm_passport_number",
				"read_only": 1,
			},
			{
				"fieldname": "one_fm_provide_accommodation_by_company",
				"label": "Provide Accommodation by Company",
				"fieldtype": "Check",
				"insert_after": "offer_terms",
			},
			{
				"fieldname": "one_fm_provide_salary_advance",
				"label": "Provide Salary Advance",
				"fieldtype": "Check",
				"insert_after": "nationality",
			},
			{
				"fieldname": "one_fm_provide_transportation_by_company",
				"label": "Provide Transportation by Company",
				"fieldtype": "Check",
				"insert_after": "one_fm_provide_accommodation_by_company",
			},
			{
				"fieldname": "one_fm_salary_advance_amount",
				"label": "Salary Advance Amount",
				"fieldtype": "Currency",
				"insert_after": "one_fm_provide_salary_advance",
				"depends_on": "one_fm_provide_salary_advance",
				"default": "30",
			},
			{
				"fieldname": "one_fm_salary_advance_paid",
				"label": "Salary Advance Paid",
				"fieldtype": "Check",
				"insert_after": "one_fm_salary_advance_amount",
				"hidden": 1,
			},
			{
				"fieldname": "one_fm_salary_details",
				"label": "Salary Details",
				"fieldtype": "Table",
				"options": "ERF Salary Detail",
				"insert_after": "one_fm_salary_structure",
			},
			{
				"fieldname": "one_fm_salary_details_section",
				"fieldtype": "Section Break",
				"insert_after": "residency_fine_amount",
			},
			{
				"fieldname": "one_fm_salary_structure",
				"label": "Salary Structure",
				"fieldtype": "Link",
				"options": "Salary Structure",
				"insert_after": "base",
			},
			{
				"fieldname": "operations_shift",
				"label": "Shift Allocation",
				"fieldtype": "Link",
				"options": "Operations Shift",
				"insert_after": "shift_working",
				"depends_on": "eval:!doc.attendance_by_timesheet",
				"fetch_from": "one_fm_erf.operations_shift",
				"fetch_if_empty": 1,
				"allow_on_submit": 1,
				"ignore_user_permissions": 1,
			},
			{
				"fieldname": "operations_site",
				"label": "Site Allocation",
				"fieldtype": "Link",
				"options": "Operations Site",
				"insert_after": "default_shift",
				"depends_on": "eval:doc.shift_working==1 && !doc.attendance_by_timesheet",
				"fetch_from": "operations_shift.site",
				"fetch_if_empty": 1,
				"read_only": 1,
				"allow_on_submit": 1,
				"ignore_user_permissions": 1,
			},
			{
				"fieldname": "project",
				"label": "Project Allocation",
				"fieldtype": "Link",
				"options": "Project",
				"insert_after": "operations_site",
				"fetch_from": "operations_shift.project",
				"fetch_if_empty": 1,
				"read_only": 1,
				"allow_on_submit": 1,
				"ignore_user_permissions": 1,
			},
			{
				"fieldname": "reason_for_rejection",
				"label": "Reason for Rejection",
				"fieldtype": "Small Text",
				"insert_after": "terms",
				"depends_on": "eval:doc.status=='Rejected'",
				"translatable": 1,
			},
			{
				"fieldname": "reports_to",
				"label": "Reports To",
				"fieldtype": "Link",
				"options": "Employee",
				"insert_after": "project",
				"allow_on_submit": 1,
				"ignore_user_permissions": 1,
			},
			{
				"fieldname": "residency_fine_amount",
				"label": "Residency Fine Amount",
				"fieldtype": "Currency",
				"insert_after": "is_residency_fine_needed",
				"depends_on": "is_residency_fine_needed",
				"allow_on_submit": 1,
			},
			{
				"fieldname": "shift_working",
				"label": "Shift Working",
				"fieldtype": "Check",
				"insert_after": "shift_working_html",
				"fetch_from": "one_fm_erf.shift_working",
				"fetch_if_empty": 1,
				"hidden": 1,
				"allow_on_submit": 1,
			},
			{
				"fieldname": "shift_working_html",
				"label": "Shift Working Html",
				"fieldtype": "HTML",
				"insert_after": "attendance_by_timesheet",
				"depends_on": "eval:!doc.attendance_by_timesheet",
			},
			{
				"fieldname": "url_qr_code",
				"label": "URL QR Code",
				"fieldtype": "Small Text",
				"insert_after": "letter_head",
				"hidden": 1,
				"translatable": 1,
				"print_hide": 1,
			},
			{
				"fieldname": "url_qr_code_image",
				"label": "URL QR Code Image",
				"fieldtype": "Image",
				"options": "url_qr_code",
				"insert_after": "url_qr_code",
				"description": "Job Offer URL QR Code",
			},
			{
				"fieldname": "workflow_state",
				"label": "Workflow State",
				"fieldtype": "Link",
				"options": "Workflow State",
				"hidden": 1,
				"allow_on_submit": 1,
				"no_copy": 1,
			},
		],
	}
