def get_project_custom_fields():
	return {
		"Project": [
			{
				"fieldname": "column_break_64",
				"fieldtype": "Column Break",
				"insert_after": "no_of_posts_as_per_contract",
			},
			{
				"fieldname": "contact_html",
				"label": "Contact Html",
				"fieldtype": "HTML",
				"insert_after": "poc_list",
			},
			{
				"fieldname": "contract_details",
				"label": "Contract Details",
				"fieldtype": "Section Break",
				"insert_after": "message",
				"depends_on": "eval:doc.project_type==\"External\"",
			},
			{
				"fieldname": "contract_duration",
				"label": "Contract Duration",
				"fieldtype": "Data",
				"insert_after": "contract_details",
				"translatable": 1,
			},
			{
				"fieldname": "custom_column_break_acgz2",
				"fieldtype": "Column Break",
				"insert_after": "custom_evidence_of_completion",
			},
			{
				"fieldname": "custom_column_break_vf2fc",
				"fieldtype": "Column Break",
				"insert_after": "custom_project_duration_weeks",
			},
			{
				"fieldname": "custom_column_break_wla9l",
				"fieldtype": "Column Break",
				"insert_after": "custom_payroll_start_date",
			},
			{
				"fieldname": "custom_end_date",
				"label": "End Date",
				"fieldtype": "Date",
				"insert_after": "custom_column_break_vf2fc",
			},
			{
				"fieldname": "custom_evidence_of_completion",
				"label": "Evidence of Completion",
				"fieldtype": "Attach",
				"insert_after": "custom_project_outcome",
				"description": "Attach document signifying project's completion",
			},
			{
				"fieldname": "custom_exclude_from_default_shift_checker",
				"label": "Exclude from Default Shift Checker",
				"fieldtype": "Check",
				"insert_after": "exempt_auto_employee_schedule",
				"depends_on": "eval:doc.project_type != \"Internal\"",
				"description": "If set to True, all Employees allocated under this project will not be considered in Default Shift Checker.",
			},
			{
				"fieldname": "custom_meeting_frequency",
				"label": "Meeting Frequency",
				"fieldtype": "Small Text",
				"insert_after": "custom_project_duration_weeks",
			},
			{
				"fieldname": "custom_milestones_and_meeting_dates",
				"label": "Milestones and Meeting Dates",
				"fieldtype": "Table",
				"options": "Milestones and Meeting Dates",
				"insert_after": "custom_end_date",
			},
			{
				"fieldname": "custom_payroll_end_date",
				"label": "Payroll End Date",
				"fieldtype": "Select",
				"options": "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31",
				"insert_after": "custom_column_break_wla9l",
				"translatable": 1,
			},
			{
				"fieldname": "custom_payroll_frequency",
				"label": "Payroll Frequency",
				"fieldtype": "Section Break",
				"insert_after": "poc",
				"depends_on": "eval:doc.project_type != \"Internal\"",
			},
			{
				"fieldname": "custom_payroll_start_date",
				"label": "Payroll Start Date",
				"fieldtype": "Select",
				"options": "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31",
				"insert_after": "custom_payroll_frequency",
				"translatable": 1,
			},
			{
				"fieldname": "custom_project_communication",
				"label": "Project Communication",
				"fieldtype": "Check",
				"insert_after": "custom_meeting_frequency",
				"description": "Make Sure to create a Google Chat or Google Space",
			},
			{
				"fieldname": "custom_project_duration_weeks",
				"label": "Project Duration (Weeks)",
				"fieldtype": "Data",
				"insert_after": "custom_start_date",
				"read_only": 1,
			},
			{
				"fieldname": "custom_project_manager_user",
				"label": "Project Manager User",
				"fieldtype": "Link",
				"options": "User",
				"insert_after": "copied_from",
				"fetch_from": "project_manager.user_id",
			},
			{
				"fieldname": "custom_project_outcome",
				"label": "Project Outcome",
				"fieldtype": "Text",
				"insert_after": "custom_project_outcome_summary",
				"description": "This project must answer three questions: <br>Why are we doing this (its connection to company goals)?<br> What is the successful outcome we need (the Key Result)? <br> And how will we get there (the list of required stories/tasks)?",
			},
			{
				"fieldname": "custom_section_break_xvhtn",
				"label": "Project Outcome",
				"fieldtype": "Section Break",
				"insert_after": "custom_exclude_from_default_shift_checker",
				"depends_on": "eval:doc.project_type == \"Internal\"",
				"collapsible": 1,
			},
			{
				"fieldname": "custom_sprint_prefix",
				"label": "Sprint Prefix",
				"fieldtype": "Data",
				"insert_after": "type",
				"depends_on": "eval: doc.type==\"SCRUM\"",
				"mandatory_depends_on": "eval: doc.type==\"SCRUM\"",
			},
			{
				"fieldname": "custom_start_date",
				"label": "Start Date",
				"fieldtype": "Date",
				"insert_after": "custom_work_project_structure",
			},
			{
				"fieldname": "custom_success_and_completion_criteria",
				"label": "Success and Completion Criteria",
				"fieldtype": "Text",
				"insert_after": "custom_column_break_acgz2",
				"description": "What signifies the project’s completion?",
			},
			{
				"fieldname": "custom_success_metrics",
				"label": "Success Metrics",
				"fieldtype": "Text",
				"insert_after": "custom_success_and_completion_criteria",
				"description": "Define the metric of success",
			},
			{
				"fieldname": "custom_work_project_structure",
				"label": "Work Project Structure",
				"fieldtype": "Section Break",
				"insert_after": "custom_success_metrics",
				"depends_on": "eval:doc.project_type == \"Internal\"",
				"collapsible": 1,
			},
			{
				"fieldname": "exempt_auto_employee_schedule",
				"label": "Exempt Auto Employee Schedule",
				"fieldtype": "Check",
				"insert_after": "project_image",
				"depends_on": "eval:doc.project_type != \"Internal\"",
			},
			{
				"fieldname": "github_sync_id",
				"label": "GitHub Sync ID",
				"fieldtype": "Data",
				"read_only": 1,
				"hidden": 1,
				"unique": 1,
				"no_copy": 1,
			},
			{
				"fieldname": "has_overtime_rate",
				"label": "Has Overtime Rate",
				"fieldtype": "Check",
				"insert_after": "number_of_posts",
				"depends_on": "eval:doc.project_type == \"External\"",
			},
			{
				"fieldname": "income_account",
				"label": "Default Income Account",
				"fieldtype": "Link",
				"options": "Account",
				"insert_after": "cost_center",
			},
			{
				"fieldname": "no_of_posts_as_per_contract",
				"label": "No of Posts as per Contract",
				"fieldtype": "Int",
				"insert_after": "contract_duration",
			},
			{
				"fieldname": "number_of_posts",
				"label": "Number of Posts",
				"fieldtype": "Int",
				"insert_after": "number_of_shifts",
			},
			{
				"fieldname": "number_of_shifts",
				"label": "Number of Shifts",
				"fieldtype": "Int",
				"insert_after": "number_of_sites",
			},
			{
				"fieldname": "number_of_sites",
				"label": "Number of Sites",
				"fieldtype": "Int",
				"insert_after": "column_break_64",
			},
			{
				"fieldname": "one_fm_project_code",
				"label": "Project Code",
				"fieldtype": "Data",
				"insert_after": "github_sync_id",
				"hidden": 1,
			},
			{
				"fieldname": "overtime_rate",
				"label": "Overtime Rate",
				"fieldtype": "Float",
				"insert_after": "has_overtime_rate",
				"depends_on": "eval:doc.has_overtime_rate==1",
				"description": "Overtime rate per hour",
				"precision": "3",
			},
			{
				"fieldname": "poc",
				"label": "POC",
				"fieldtype": "Table",
				"options": "POC",
				"insert_after": "contact_html",
			},
			{
				"fieldname": "poc_list",
				"label": "POC List",
				"fieldtype": "Section Break",
				"insert_after": "overtime_rate",
				"depends_on": "eval:doc.project_type==\"External\"",
			},
			{
				"fieldname": "project_image",
				"label": "Project Image",
				"fieldtype": "Attach Image",
				"insert_after": "department",
				"depends_on": "eval:doc.project_type != \"Internal\"",
			},
			{
				"fieldname": "project_manager",
				"label": "Project Manager",
				"fieldtype": "Link",
				"options": "Employee",
				"insert_after": "users_section",
				"mandatory_depends_on": "eval:doc.project_type==\"External\"",
				"ignore_user_permissions": 1,
			},
			{
				"fieldname": "project_manager_name",
				"label": "Project Manager Name",
				"fieldtype": "Data",
				"insert_after": "project_manager",
				"fetch_from": "project_manager.employee_name",
				"read_only": 1,
				"translatable": 1,
			},
			{
				"fieldname": "project_name_in_arabic",
				"label": "Project Name In Arabic",
				"fieldtype": "Data",
				"insert_after": "project_name",
				"depends_on": "eval:doc.project_type != \"Internal\"",
				"translatable": 1,
			},
			{
				"fieldname": "show_in_roadmap",
				"label": "Show in Roadmap",
				"fieldtype": "Select",
				"options": "\nYes\nNo",
				"insert_after": "custom_sprint_prefix",
				"depends_on": "eval: doc.type==\"SCRUM\"",
				"mandatory_depends_on": "eval: doc.type==\"SCRUM\"",
			},
			{
				"fieldname": "site_section_01",
				"label": "Project Sites",
				"fieldtype": "Section Break",
				"insert_after": "copied_from",
				"collapsible": 1,
			},
			{
				"fieldname": "total_depreciation_expense",
				"label": "Total Depreciation Expense",
				"fieldtype": "Currency",
				"options": "currency",
				"insert_after": "total_purchase_cost",
				"read_only": 1,
			},
			{
				"fieldname": "total_expense_claim",
				"label": "Total Expense Claim (via Expense Claims)",
				"fieldtype": "Currency",
				"insert_after": "total_costing_amount",
				"read_only": 1,
			},
			{
				"fieldname": "type",
				"label": "Type",
				"fieldtype": "Data",
				"insert_after": "project_type",
				"depends_on": "eval: doc.type==\"SCRUM\"",
				"read_only_depends_on": "eval: doc.type==\"SCRUM\"",
				"fetch_from": "project_type.type",
				"translatable": 1,
			},
		],
	}
