services:
  backend:
    image: one-fm:latest
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: ${REMOTE_DB_HOST}
      DB_PORT: ${REMOTE_DB_PORT}
      MARIADB_ROOT_PASSWORD: ${REMOTE_DB_ROOT_PASSWORD}

  configurator:
    image: one-fm:latest
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - -c
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: ${REMOTE_DB_HOST}
      DB_PORT: "${REMOTE_DB_PORT}"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  create-site:
    image: one-fm:latest
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: none
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: ${REMOTE_DB_HOST}
      DB_PORT: ${REMOTE_DB_PORT}
      DB_NAME: ${REMOTE_DB_NAME}
      ROOT_USERNAME: ${REMOTE_DB_ROOT_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${REMOTE_DB_ROOT_PASSWORD}
      FRAPPE_SITE_NAME_HEADER: ${FRAPPE_SITE_NAME}
    entrypoint:
      - bash
      - -c
    command:
      - >
        echo $$DB_HOST;
        wait-for-it -t 120 $$DB_HOST:$$DB_PORT;
        wait-for-it -t 120 redis-cache:6379;
        wait-for-it -t 120 redis-queue:6379;
        export start=`date +%s`;
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep 5;
          if (( `date +%s`-start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1
          fi
        done;
        echo "sites/common_site_config.json found";

        SITE_NAME="$${FRAPPE_SITE_NAME_HEADER}";
        echo "Checking if site '$${SITE_NAME}' exists...";

        if bench --site "$${SITE_NAME}" ls >/dev/null 2>&1; then
          echo "Site exists: $${SITE_NAME}";
          echo "Installing apps on existing site...";

          bench --site "$${SITE_NAME}" install-app erpnext;
          bench --site "$${SITE_NAME}" install-app hrms;
          bench --site "$${SITE_NAME}" install-app telephony;
          bench --site "$${SITE_NAME}" install-app lending;
          bench --site "$${SITE_NAME}" install-app helpdesk;
          bench --site "$${SITE_NAME}" install-app one_fm;

        else
          echo "Site does NOT exist. Creating new site: $${SITE_NAME}";

          bench new-site "$${SITE_NAME}" \
            --mariadb-user-host-login-scope='%' \
            --admin-password="$${ADMIN_PASSWORD}" \
            --db-root-username="$${ROOT_USERNAME}" \
            --db-root-password="$${MARIADB_ROOT_PASSWORD}" \
            --db-name="$$DB_NAME" \
            --install-app erpnext \
            --install-app hrms \
            --install-app telephony \
            --install-app lending \
            --install-app helpdesk \
            --install-app one_fm \
            --set-default;
        fi;

        bench --site "$${SITE_NAME}" migrate;
    

  frontend:
    image: one-fm:latest
    networks:
      - frappe_network
    depends_on:
      - websocket
    deploy:
      restart_policy:
        condition: on-failure
    command:
      sh -c "bench build --production && nginx-entrypoint.sh"
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: ${FRAPPE_SITE_NAME}
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    ports:
      - "8080:8080"

  queue-long:
    image: one-fm:latest
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      FRAPPE_REDIS_CACHE: redis://redis-cache:6379
      FRAPPE_REDIS_QUEUE: redis://redis-queue:6379

  queue-short:
    image: one-fm:latest
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - short,default
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      FRAPPE_REDIS_CACHE: redis://redis-cache:6379
      FRAPPE_REDIS_QUEUE: redis://redis-queue:6379

  redis-queue:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure

  scheduler:
    image: one-fm:latest
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  websocket:
    image: one-fm:latest
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    environment:
      FRAPPE_REDIS_CACHE: redis://redis-cache:6379
      FRAPPE_REDIS_QUEUE: redis://redis-queue:6379
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

volumes:
  redis-queue-data:
  sites:
  logs:

networks:
  frappe_network:
    driver: bridge
