"""Apply the customizations Processa synced for: Process Creation Request.

Generated by Processa (Review Doctypes → Sync) for process map
``Process Creation - v2``. The data lives in the custom/ modules imported below --
this patch only applies it to a site that already exists. Fresh installs
get the same content through setup/setup.py's after_install.

Idempotent: create_custom_fields(update=True) updates a field that is
already there instead of failing, and make_property_setter overwrites the
property it owns.
"""

from frappe.custom.doctype.custom_field.custom_field import create_custom_fields

from one_fm.setup.setup import add_property_setter
from one_fm.custom.custom_field.process_creation_request import get_process_creation_request_custom_fields
from one_fm.custom.property_setter.process_creation_request import get_process_creation_request_properties


def execute():
	create_custom_fields(get_process_creation_request_custom_fields(), update=True)
	add_property_setter(get_process_creation_request_properties())
