/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardPool: typeof import('./src/components/CardPool.vue')['default']
    DetailPanel: typeof import('./src/components/DetailPanel.vue')['default']
    ManifestVehicle: typeof import('./src/components/ManifestVehicle.vue')['default']
    ManifestView: typeof import('./src/components/ManifestView.vue')['default']
    MergedBlock: typeof import('./src/components/MergedBlock.vue')['default']
    PlanHeader: typeof import('./src/components/PlanHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShipmentCard: typeof import('./src/components/ShipmentCard.vue')['default']
    SwimBlock: typeof import('./src/components/SwimBlock.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    TimelineGrid: typeof import('./src/components/TimelineGrid.vue')['default']
  }
}
