# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import facial_recognition_pb2 as facial__recognition__pb2


class FaceRecognitionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FaceRecognition = channel.unary_unary(
                '/FaceRecognitionService/FaceRecognition',
                request_serializer=facial__recognition__pb2.Request.SerializeToString,
                response_deserializer=facial__recognition__pb2.Response.FromString,
                )


class FaceRecognitionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FaceRecognition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceRecognitionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FaceRecognition': grpc.unary_unary_rpc_method_handler(
                    servicer.FaceRecognition,
                    request_deserializer=facial__recognition__pb2.Request.FromString,
                    response_serializer=facial__recognition__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FaceRecognitionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FaceRecognitionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FaceRecognition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FaceRecognitionService/FaceRecognition',
            facial__recognition__pb2.Request.SerializeToString,
            facial__recognition__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
