def get_employee_separation_properties():
	return [
		{
			"doctype_or_field": "DocType",
			"doc_type": "Employee Separation",
			"field_name": None,
			"property": "field_order",
			"property_type": "Data",
			"value": "[\"mode_of_separation\", \"relieving_date\", \"type_of_exit\", \"workflow_state\", \"employee\", \"employee_name\", \"department\", \"designation\", \"employee_grade\", \"column_break_7\", \"company\", \"boarding_status\", \"resignation_letter_date\", \"boarding_begins_on\", \"project\", \"table_for_activity\", \"employee_separation_template\", \"activities\", \"notify_users_by_email\", \"section_break_14\", \"exit_interview\", \"amended_from\"]",
		},
		{
			"doctype_or_field": "DocField",
			"doc_type": "Employee Separation",
			"field_name": "boarding_begins_on",
			"property": "fetch_from",
			"property_type": "Small Text",
			"value": "employee.relieving_date",
		},
		{
			"doctype_or_field": "DocField",
			"doc_type": "Employee Separation",
			"field_name": "boarding_begins_on",
			"property": "fetch_if_empty",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doctype_or_field": "DocField",
			"doc_type": "Employee Separation",
			"field_name": "boarding_begins_on",
			"property": "label",
			"property_type": "Data",
			"value": "Relieving Date",
		},
		{
			"doctype_or_field": "DocField",
			"doc_type": "Employee Separation",
			"field_name": "boarding_begins_on",
			"property": "reqd",
			"property_type": "Check",
			"value": "0",
		},
		{
			"doctype_or_field": "DocField",
			"doc_type": "Employee Separation",
			"field_name": "designation",
			"property": "fetch_if_empty",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doctype_or_field": "DocField",
			"doc_type": "Employee Separation",
			"field_name": "project",
			"property": "fetch_from",
			"property_type": "Small Text",
			"value": "employee.project_allocation",
		},
		{
			"doctype_or_field": "DocField",
			"doc_type": "Employee Separation",
			"field_name": "project",
			"property": "fetch_if_empty",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doctype_or_field": "DocField",
			"doc_type": "Employee Separation",
			"field_name": "project",
			"property": "label",
			"property_type": "Data",
			"value": "Project Allocation",
		},
		{
			"doctype_or_field": "DocField",
			"doc_type": "Employee Separation",
			"field_name": "relieving_date",
			"property": "fetch_from",
			"property_type": "Small Text",
			"value": "employee.relieving _date",
		},
		{
			"doctype_or_field": "DocField",
			"doc_type": "Employee Separation",
			"field_name": "type_of_exit",
			"property": "fieldtype",
			"property_type": "Select",
			"value": "Select",
		},
		{
			"doctype_or_field": "DocField",
			"doc_type": "Employee Separation",
			"field_name": "type_of_exit",
			"property": "in_list_view",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doctype_or_field": "DocField",
			"doc_type": "Employee Separation",
			"field_name": "type_of_exit",
			"property": "options",
			"property_type": "Text",
			"value": "Expat Cancellation\nLocal Transfer\nKuwaiti Cancellation",
		},
		{
			"doctype_or_field": "DocField",
			"doc_type": "Employee Separation",
			"field_name": "type_of_exit",
			"property": "reqd",
			"property_type": "Check",
			"value": "1",
		},
	]
