# When updating this file, please also update the linter_workflow_template in frappe/utils/boilerplate.py
name: Linters

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: commitcheck-frappe-${{ github.event_name }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  commit-lint:
    name: 'Semantic Commits'
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 200
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true

      - name: Check commit titles
        run: |
          npm install @commitlint/cli @commitlint/config-conventional
          npx commitlint --verbose --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }}

  linter:
    name: 'Semgrep Rules'
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.14'
          cache: pip

      - name: Download Semgrep rules
        run: git clone --depth 1 https://github.com/frappe/semgrep-rules.git frappe-semgrep-rules

      - name: Run Semgrep rules
        run: |
          pip install semgrep
          semgrep ci --config ./frappe-semgrep-rules/rules --config r/python.lang.correctness

  deps-vulnerable-check:
    name: 'Vulnerable Dependency Check'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt', '**/pyproject.toml', '**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install and run pip-audit
        run: |
          pip install pip-audit
          cd ${GITHUB_WORKSPACE}
          pip-audit --desc on \
            --ignore-vuln GHSA-4xqq-73wg-5mjp \
            --ignore-vuln PYSEC-2023-312 \
            --ignore-vuln PYSEC-2022-252 \
            --ignore-vuln CVE-2026-44405 \
            --ignore-vuln PYSEC-2025-11 \
            --ignore-vuln PYSEC-2026-85 \
            --ignore-vuln PYSEC-2026-86 \
            --ignore-vuln CVE-2024-12704 \
            --ignore-vuln CVE-2024-12911 \
            --ignore-vuln CVE-2025-1793 \
            --ignore-vuln CVE-2025-6211 \
            --ignore-vuln CVE-2025-7707 \
            --ignore-vuln CVE-2025-5472 \
            --ignore-vuln CVE-2025-5302 \
            --ignore-vuln CVE-2025-7647 \
            --ignore-vuln CVE-2025-6208 \
            --ignore-vuln CVE-2025-1753 \
            --ignore-vuln CVE-2025-55197 \
            --ignore-vuln CVE-2025-62707 \
            --ignore-vuln CVE-2025-62708 \
            --ignore-vuln CVE-2025-66019 \
            --ignore-vuln CVE-2026-22690 \
            --ignore-vuln CVE-2026-22691 \
            --ignore-vuln CVE-2026-24688 \
            --ignore-vuln CVE-2026-27026 \
            --ignore-vuln CVE-2026-27024 \
            --ignore-vuln CVE-2026-27025 \
            --ignore-vuln CVE-2026-27628 \
            --ignore-vuln CVE-2026-27888 \
            --ignore-vuln CVE-2026-28351 \
            --ignore-vuln CVE-2026-28804 \
            --ignore-vuln CVE-2026-31826 \
            --ignore-vuln CVE-2026-33123 \
            --ignore-vuln CVE-2026-33699 \
            --ignore-vuln CVE-2026-40260 \
            --ignore-vuln CVE-2026-41168 \
            --ignore-vuln CVE-2026-41313 \
            --ignore-vuln CVE-2026-41312 \
            --ignore-vuln CVE-2026-41314 \
            .
