name: Deploy CI/CD to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Deploy to Staging
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.STAGING_KEY }}
          port: 22
          command_timeout: 30m
          script_stop: true
          script: |
            set -x
            cd /home/frappe/frappe-bench/apps/one_fm
            git pull upstream staging
            cd /home/frappe/frappe-bench
            bench setup requirements one_fm
            bench migrate
            bench build --app one_fm
            bench clear-cache
            bench restart
