name: Deploy CI/CD to Test production

on:
  push: # tells github to run this on any push to the repository
    branches:
      - master-14

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 40

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy to Test Production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LMS_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.LMS_SECRET }}
        port: 22
        script: |
          cd /home/frappe/master-14/apps/one_fm # we move into our app's folder
          git pull upstream test-production # we pull any changes from git
          cd /home/frappe/master-14
          sudo supervisorctl restart all
          ${{ secrets.PASSKEY }}
          bench migrate # sync database
           # we remove any unused dependencies
          bench doctor
