name: Deploy CI/CD to Test Production

on:
  push: # tells github to run this on any push to the repository
    branches:
      - test-production

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 90

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy to Test Production
      uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.STAGING_KEY }}
        port: 22
        script: |
          cd /home/frappe/test-production/apps/one_fm
          git pull upstream test-production
          cd /home/frappe/test-production   
          bench setup requirements one_fm
          bench migrate
          bench build --app one_fm
          bench clear-cache
          bench restart
