# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from one_fm.proto import enroll_pb2 as one__fm_dot_proto_dot_enroll__pb2


class FaceRecognitionEnrollmentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FaceRecognitionEnroll = channel.unary_unary(
                '/FaceRecognitionEnrollmentService/FaceRecognitionEnroll',
                request_serializer=one__fm_dot_proto_dot_enroll__pb2.EnrollRequest.SerializeToString,
                response_deserializer=one__fm_dot_proto_dot_enroll__pb2.EnrollResponse.FromString,
                )


class FaceRecognitionEnrollmentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FaceRecognitionEnroll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceRecognitionEnrollmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FaceRecognitionEnroll': grpc.unary_unary_rpc_method_handler(
                    servicer.FaceRecognitionEnroll,
                    request_deserializer=one__fm_dot_proto_dot_enroll__pb2.EnrollRequest.FromString,
                    response_serializer=one__fm_dot_proto_dot_enroll__pb2.EnrollResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FaceRecognitionEnrollmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FaceRecognitionEnrollmentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FaceRecognitionEnroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FaceRecognitionEnrollmentService/FaceRecognitionEnroll',
            one__fm_dot_proto_dot_enroll__pb2.EnrollRequest.SerializeToString,
            one__fm_dot_proto_dot_enroll__pb2.EnrollResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
