# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/enroll.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/enroll.proto\"7\n\x07Request\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x1a\n\x12user_encoded_video\x18\x02 \x01(\t\"O\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x12\n\nenrollment\x18\x04 \x01(\t2P\n FaceRecognitionEnrollmentService\x12,\n\x15\x46\x61\x63\x65RecognitionEnroll\x12\x08.Request\x1a\t.Responseb\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'proto.enroll_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'proto.enroll_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

_FACERECOGNITIONENROLLMENTSERVICE = DESCRIPTOR.services_by_name['FaceRecognitionEnrollmentService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=22
  _REQUEST._serialized_end=77
  _RESPONSE._serialized_start=79
  _RESPONSE._serialized_end=158
  _FACERECOGNITIONENROLLMENTSERVICE._serialized_start=160
  _FACERECOGNITIONENROLLMENTSERVICE._serialized_end=240
# @@protoc_insertion_point(module_scope)
