# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: one_fm/proto/enroll.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19one_fm/proto/enroll.proto\"=\n\rEnrollRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x1a\n\x12user_encoded_video\x18\x02 \x01(\t\"U\n\x0e\x45nrollResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x12\n\nenrollment\x18\x04 \x01(\t2\\\n FaceRecognitionEnrollmentService\x12\x38\n\x15\x46\x61\x63\x65RecognitionEnroll\x12\x0e.EnrollRequest\x1a\x0f.EnrollResponseb\x06proto3')



_ENROLLREQUEST = DESCRIPTOR.message_types_by_name['EnrollRequest']
_ENROLLRESPONSE = DESCRIPTOR.message_types_by_name['EnrollResponse']
EnrollRequest = _reflection.GeneratedProtocolMessageType('EnrollRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENROLLREQUEST,
  '__module__' : 'one_fm.proto.enroll_pb2'
  # @@protoc_insertion_point(class_scope:EnrollRequest)
  })
_sym_db.RegisterMessage(EnrollRequest)

EnrollResponse = _reflection.GeneratedProtocolMessageType('EnrollResponse', (_message.Message,), {
  'DESCRIPTOR' : _ENROLLRESPONSE,
  '__module__' : 'one_fm.proto.enroll_pb2'
  # @@protoc_insertion_point(class_scope:EnrollResponse)
  })
_sym_db.RegisterMessage(EnrollResponse)

_FACERECOGNITIONENROLLMENTSERVICE = DESCRIPTOR.services_by_name['FaceRecognitionEnrollmentService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENROLLREQUEST._serialized_start=29
  _ENROLLREQUEST._serialized_end=90
  _ENROLLRESPONSE._serialized_start=92
  _ENROLLRESPONSE._serialized_end=177
  _FACERECOGNITIONENROLLMENTSERVICE._serialized_start=179
  _FACERECOGNITIONENROLLMENTSERVICE._serialized_end=271
# @@protoc_insertion_point(module_scope)
