# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: one_fm/proto/facial_recognition.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%one_fm/proto/facial_recognition.proto\"U\n\x16\x46\x61\x63\x65RecognitionRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x15\n\rmedia_content\x18\x02 \x01(\t\x12\x12\n\nmedia_type\x18\x03 \x01(\t\"`\n\x17\x46\x61\x63\x65RecognitionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x14\n\x0cverification\x18\x04 \x01(\t2^\n\x16\x46\x61\x63\x65RecognitionService\x12\x44\n\x0f\x46\x61\x63\x65Recognition\x12\x17.FaceRecognitionRequest\x1a\x18.FaceRecognitionResponseb\x06proto3')



_FACERECOGNITIONREQUEST = DESCRIPTOR.message_types_by_name['FaceRecognitionRequest']
_FACERECOGNITIONRESPONSE = DESCRIPTOR.message_types_by_name['FaceRecognitionResponse']
FaceRecognitionRequest = _reflection.GeneratedProtocolMessageType('FaceRecognitionRequest', (_message.Message,), {
  'DESCRIPTOR' : _FACERECOGNITIONREQUEST,
  '__module__' : 'one_fm.proto.facial_recognition_pb2'
  # @@protoc_insertion_point(class_scope:FaceRecognitionRequest)
  })
_sym_db.RegisterMessage(FaceRecognitionRequest)

FaceRecognitionResponse = _reflection.GeneratedProtocolMessageType('FaceRecognitionResponse', (_message.Message,), {
  'DESCRIPTOR' : _FACERECOGNITIONRESPONSE,
  '__module__' : 'one_fm.proto.facial_recognition_pb2'
  # @@protoc_insertion_point(class_scope:FaceRecognitionResponse)
  })
_sym_db.RegisterMessage(FaceRecognitionResponse)

_FACERECOGNITIONSERVICE = DESCRIPTOR.services_by_name['FaceRecognitionService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FACERECOGNITIONREQUEST._serialized_start=41
  _FACERECOGNITIONREQUEST._serialized_end=126
  _FACERECOGNITIONRESPONSE._serialized_start=128
  _FACERECOGNITIONRESPONSE._serialized_end=224
  _FACERECOGNITIONSERVICE._serialized_start=226
  _FACERECOGNITIONSERVICE._serialized_end=320
# @@protoc_insertion_point(module_scope)
